import type { Rule, RulePack } from '@certa/core';

function formatValue(rule: Rule): string {
  switch (rule.kind) {
    case 'duration':
      return `${rule.value.amount} ${rule.value.unit}${rule.value.roundTo === 'end_of_month' ? ' (to end of month)' : ''}`;
    case 'length':
    case 'speed':
    case 'mass':
      return `${rule.value} ${rule.unit}`;
    case 'money':
      return `${(rule.value / 100).toFixed(2)} ${rule.unit}`;
    default:
      return String(rule.value);
  }
}

const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** Renders docs/RULES_VERIFICATION.md from the pack files so the checklist can never drift. */
export function renderVerificationDoc(packs: RulePack[]): string {
  const lines: string[] = [
    '# Rules Verification Checklist',
    '',
    '<!-- GENERATED by `pnpm rules:verify-doc` from packages/rulepacks/packs. Do not edit by hand. -->',
    '',
    'Every regulatory value Certa ships is listed here. Before launch, a qualified team member must',
    'confirm each value against the cited official source, then in the pack file set',
    '`needsVerification: false` and `lastVerifiedOn` to the verification date, and regenerate this file.',
    '',
    '> Certa is a record-keeping tool. Operators remain responsible for compliance.',
    '',
  ];
  for (const pack of packs) {
    const pending = pack.rules.filter((r) => r.needsVerification).length;
    lines.push(
      `## ${pack.jurisdiction} @ ${pack.version} — ${pack.name}`,
      '',
      `Authority: ${pack.authority}. Effective from ${pack.effectiveFrom}. **${pending} of ${pack.rules.length} values pending verification.**`,
      '',
      '| ☐ | Rule id | Value (SI) | Stated as | Citation | Official source | Last verified |',
      '|---|---|---|---|---|---|---|',
    );
    for (const r of pack.rules) {
      lines.push(
        `| ${r.needsVerification ? '☐' : '☑'} | \`${r.id}\` | ${esc(formatValue(r))} | ${esc(r.statedAs ?? '—')} | ${esc(r.source.citation)} | ${r.source.url ? `[${esc(r.source.title)}](${r.source.url})` : esc(r.source.title)} | ${r.lastVerifiedOn ?? '—'} |`,
      );
    }
    const noted = pack.rules.filter((r) => r.notes);
    if (noted.length) {
      lines.push('', '### Notes for verifiers', '');
      for (const r of noted) lines.push(`- \`${r.id}\`: ${esc(r.notes!)}`);
    }
    lines.push('', '### Credential types', '', '| Id | Label | Expiry rule | Required for currency |', '|---|---|---|---|');
    for (const c of pack.credentialTypes)
      lines.push(`| \`${c.id}\` | ${esc(c.label)} | ${c.validityRuleId ? `\`${c.validityRuleId}\`` : 'does not expire'} | ${c.requiredForCurrency ? 'yes' : 'no'} |`);
    lines.push('');
  }
  return lines.join('\n');
}
