/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            version: string;
                            checks: {
                                [key: string]: "ok" | "fail";
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            version: string;
                            checks: {
                                [key: string]: "ok" | "fail";
                            };
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            version: string;
                            checks: {
                                [key: string]: "ok" | "fail";
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and its first organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                        organizationName: string;
                        /** @default America/New_York */
                        timezone?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                name: string;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            memberships: {
                                /** Format: uuid */
                                membershipId: string;
                                /** Format: uuid */
                                orgId: string;
                                orgName: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                requestId?: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user and their organizations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                name: string;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            memberships: {
                                /** Format: uuid */
                                membershipId: string;
                                /** Format: uuid */
                                orgId: string;
                                orgName: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an additional organization owned by the caller */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        timezone: string;
                        /** @default US-FAA-Part107 */
                        defaultJurisdiction?: string;
                        units?: {
                            /** @enum {string} */
                            length: "ft" | "m";
                            /** @enum {string} */
                            speed: "mph" | "kph" | "kt" | "mps";
                            /** @enum {string} */
                            mass: "lb" | "kg" | "g";
                            /** @enum {string} */
                            temperature: "F" | "C";
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            organization: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                slug: string;
                                /** @enum {string} */
                                planTier: "solo" | "team" | "enterprise" | "self_hosted";
                                defaultJurisdiction: string;
                                timezone: string;
                                units: {
                                    /** @enum {string} */
                                    length: "ft" | "m";
                                    /** @enum {string} */
                                    speed: "mph" | "kph" | "kt" | "mps";
                                    /** @enum {string} */
                                    mass: "lb" | "kg" | "g";
                                    /** @enum {string} */
                                    temperature: "F" | "C";
                                };
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            membership: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                orgId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                createdBy: string | null;
                                deletedAt: string | null;
                                /** Format: uuid */
                                userId: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                                auditorScope: {
                                    from: string | null;
                                    to: string | null;
                                    pilotIds: string[] | null;
                                    aircraftIds: string[] | null;
                                } | null;
                            };
                            permissions: ("org.read" | "org.update" | "org.billing" | "members.read" | "members.manage" | "rules.read" | "rules.override" | "audit.read" | "pilots.read" | "pilots.manage" | "credentials.read" | "credentials.manage" | "aircraft.read" | "aircraft.manage" | "aircraft.ground" | "aircraft.override_grounding" | "batteries.read" | "batteries.manage" | "components.manage" | "maintenance.read" | "maintenance.manage" | "flights.read" | "flights.log" | "flights.edit" | "missions.read" | "missions.manage" | "checklists.read" | "checklists.manage_templates" | "checklists.run" | "incidents.read" | "incidents.report" | "incidents.manage" | "exports.create" | "integrity.verify" | "integrations.manage")[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization, caller membership, and caller permissions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            organization: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                slug: string;
                                /** @enum {string} */
                                planTier: "solo" | "team" | "enterprise" | "self_hosted";
                                defaultJurisdiction: string;
                                timezone: string;
                                units: {
                                    /** @enum {string} */
                                    length: "ft" | "m";
                                    /** @enum {string} */
                                    speed: "mph" | "kph" | "kt" | "mps";
                                    /** @enum {string} */
                                    mass: "lb" | "kg" | "g";
                                    /** @enum {string} */
                                    temperature: "F" | "C";
                                };
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            membership: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                orgId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                createdBy: string | null;
                                deletedAt: string | null;
                                /** Format: uuid */
                                userId: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                                auditorScope: {
                                    from: string | null;
                                    to: string | null;
                                    pilotIds: string[] | null;
                                    aircraftIds: string[] | null;
                                } | null;
                            };
                            permissions: ("org.read" | "org.update" | "org.billing" | "members.read" | "members.manage" | "rules.read" | "rules.override" | "audit.read" | "pilots.read" | "pilots.manage" | "credentials.read" | "credentials.manage" | "aircraft.read" | "aircraft.manage" | "aircraft.ground" | "aircraft.override_grounding" | "batteries.read" | "batteries.manage" | "components.manage" | "maintenance.read" | "maintenance.manage" | "flights.read" | "flights.log" | "flights.edit" | "missions.read" | "missions.manage" | "checklists.read" | "checklists.manage_templates" | "checklists.run" | "incidents.read" | "incidents.report" | "incidents.manage" | "exports.create" | "integrity.verify" | "integrations.manage")[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        timezone?: string;
                        units?: {
                            /** @enum {string} */
                            length: "ft" | "m";
                            /** @enum {string} */
                            speed: "mph" | "kph" | "kt" | "mps";
                            /** @enum {string} */
                            mass: "lb" | "kg" | "g";
                            /** @enum {string} */
                            temperature: "F" | "C";
                        };
                        defaultJurisdiction?: string;
                        /** @enum {string} */
                        planTier?: "solo" | "team" | "enterprise" | "self_hosted";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            organization: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                slug: string;
                                /** @enum {string} */
                                planTier: "solo" | "team" | "enterprise" | "self_hosted";
                                defaultJurisdiction: string;
                                timezone: string;
                                units: {
                                    /** @enum {string} */
                                    length: "ft" | "m";
                                    /** @enum {string} */
                                    speed: "mph" | "kph" | "kt" | "mps";
                                    /** @enum {string} */
                                    mass: "lb" | "kg" | "g";
                                    /** @enum {string} */
                                    temperature: "F" | "C";
                                };
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            membership: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                orgId: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                createdBy: string | null;
                                deletedAt: string | null;
                                /** Format: uuid */
                                userId: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                                auditorScope: {
                                    from: string | null;
                                    to: string | null;
                                    pilotIds: string[] | null;
                                    aircraftIds: string[] | null;
                                } | null;
                            };
                            permissions: ("org.read" | "org.update" | "org.billing" | "members.read" | "members.manage" | "rules.read" | "rules.override" | "audit.read" | "pilots.read" | "pilots.manage" | "credentials.read" | "credentials.manage" | "aircraft.read" | "aircraft.manage" | "aircraft.ground" | "aircraft.override_grounding" | "batteries.read" | "batteries.manage" | "components.manage" | "maintenance.read" | "maintenance.manage" | "flights.read" | "flights.log" | "flights.edit" | "missions.read" | "missions.manage" | "checklists.read" | "checklists.manage_templates" | "checklists.run" | "incidents.read" | "incidents.report" | "incidents.manage" | "exports.create" | "integrity.verify" | "integrations.manage")[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/orgs/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            members: {
                                /** Format: uuid */
                                membershipId: string;
                                /** Format: uuid */
                                userId: string;
                                name: string;
                                /** Format: email */
                                email: string;
                                /** @enum {string} */
                                role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                                expiresAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a member (creates the user if needed and emails a sign-in link) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        name: string;
                        /** @enum {string} */
                        role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                        expiresAt?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            membershipId: string;
                            /** Format: uuid */
                            userId: string;
                            name: string;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                            expiresAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                requestId?: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{orgId}/members/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                    membershipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                    membershipId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        role?: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                        expiresAt?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            membershipId: string;
                            /** Format: uuid */
                            userId: string;
                            name: string;
                            /** Format: email */
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "admin" | "chief_pilot" | "pilot" | "maintenance_tech" | "viewer" | "auditor";
                            expiresAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/rule-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All loaded rule packs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            packs: {
                                /** Format: uuid */
                                id: string;
                                jurisdiction: string;
                                version: string;
                                name: string;
                                authority: string;
                                /** Format: date */
                                effectiveFrom: string;
                                disclaimer: string;
                                ruleCount: number;
                                unverifiedCount: number;
                                active: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{orgId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective rule pack for the organization, with overrides applied */
        get: {
            parameters: {
                query?: {
                    jurisdiction?: string;
                };
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pack: {
                                /** Format: uuid */
                                id: string;
                                jurisdiction: string;
                                version: string;
                                name: string;
                                authority: string;
                                /** Format: date */
                                effectiveFrom: string;
                                disclaimer: string;
                                ruleCount: number;
                                unverifiedCount: number;
                                active: boolean;
                            };
                            credentialTypes: {
                                id: string;
                                label: string;
                                description: string;
                                validityRuleId: string | null;
                                requiredForCurrency: boolean;
                            }[];
                            rules: {
                                id: string;
                                title: string;
                                description: string;
                                kind: string;
                                appliesTo: string;
                                value: unknown;
                                packValue: unknown;
                                unit: string | null;
                                statedAs: string | null;
                                source: {
                                    title: string;
                                    citation: string;
                                    url: string | null;
                                };
                                lastVerifiedOn: string | null;
                                needsVerification: boolean;
                                notes: string | null;
                                override: {
                                    value: unknown;
                                    reason: string;
                                    setBy: string | null;
                                    /** Format: date-time */
                                    setAt: string;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{orgId}/rules/{ruleId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Override a rule value for this organization (owner/admin, audited) */
        put: {
            parameters: {
                query?: {
                    jurisdiction?: string;
                };
                header?: never;
                path: {
                    orgId: string;
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        value: unknown;
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pack: {
                                /** Format: uuid */
                                id: string;
                                jurisdiction: string;
                                version: string;
                                name: string;
                                authority: string;
                                /** Format: date */
                                effectiveFrom: string;
                                disclaimer: string;
                                ruleCount: number;
                                unverifiedCount: number;
                                active: boolean;
                            };
                            credentialTypes: {
                                id: string;
                                label: string;
                                description: string;
                                validityRuleId: string | null;
                                requiredForCurrency: boolean;
                            }[];
                            rules: {
                                id: string;
                                title: string;
                                description: string;
                                kind: string;
                                appliesTo: string;
                                value: unknown;
                                packValue: unknown;
                                unit: string | null;
                                statedAs: string | null;
                                source: {
                                    title: string;
                                    citation: string;
                                    url: string | null;
                                };
                                lastVerifiedOn: string | null;
                                needsVerification: boolean;
                                notes: string | null;
                                override: {
                                    value: unknown;
                                    reason: string;
                                    setBy: string | null;
                                    /** Format: date-time */
                                    setAt: string;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        post?: never;
        /** Remove an override, restoring the pack value. A reason is recorded in the audit log. */
        delete: {
            parameters: {
                query?: {
                    jurisdiction?: string;
                };
                header?: never;
                path: {
                    orgId: string;
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pack: {
                                /** Format: uuid */
                                id: string;
                                jurisdiction: string;
                                version: string;
                                name: string;
                                authority: string;
                                /** Format: date */
                                effectiveFrom: string;
                                disclaimer: string;
                                ruleCount: number;
                                unverifiedCount: number;
                                active: boolean;
                            };
                            credentialTypes: {
                                id: string;
                                label: string;
                                description: string;
                                validityRuleId: string | null;
                                requiredForCurrency: boolean;
                            }[];
                            rules: {
                                id: string;
                                title: string;
                                description: string;
                                kind: string;
                                appliesTo: string;
                                value: unknown;
                                packValue: unknown;
                                unit: string | null;
                                statedAs: string | null;
                                source: {
                                    title: string;
                                    citation: string;
                                    url: string | null;
                                };
                                lastVerifiedOn: string | null;
                                needsVerification: boolean;
                                notes: string | null;
                                override: {
                                    value: unknown;
                                    reason: string;
                                    setBy: string | null;
                                    /** Format: date-time */
                                    setAt: string;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{orgId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Append-only audit log, newest first */
        get: {
            parameters: {
                query?: {
                    table?: string;
                    rowId?: string;
                    actorUserId?: string;
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events: {
                                id: number;
                                orgId: string | null;
                                /** Format: date-time */
                                at: string;
                                actorUserId: string | null;
                                requestId: string | null;
                                tableName: string;
                                rowId: string;
                                /** @enum {string} */
                                operation: "INSERT" | "UPDATE" | "DELETE";
                                before: {
                                    [key: string]: unknown;
                                } | null;
                                after: {
                                    [key: string]: unknown;
                                } | null;
                                actorName: string | null;
                            }[];
                            nextBefore: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
