import { CERTA_MARK, CERTA_WORDMARK, MARK_VIEWBOX } from './brand-marks';

/**
 * Certa mark: the Arkhon triangle with a check cut through it in negative space — the verified
 * record. Geometry is generated by brand/build.py (see brand/README.md); don't redraw it here.
 */
export function CertaMark({ className, title }: { className?: string; title?: string }) {
  return (
    <svg viewBox={MARK_VIEWBOX} width="1em" height="1em" className={className} role={title ? 'img' : undefined} aria-label={title} aria-hidden={title ? undefined : true}>
      <path d={CERTA_MARK} fill="currentColor" fillRule="evenodd" />
    </svg>
  );
}

/**
 * Lockup: mark + outlined Geist wordmark (identical on every device), optionally endorsed
 * "by Arkhon Industries". `height` is the mark height in px; everything scales from it.
 */
export function CertaLogo({ height = 28, endorsed = false, className }: { height?: number; endorsed?: boolean; className?: string }) {
  const k = (height * 0.62) / 40; // wordmark size relative to the mark
  const w = CERTA_WORDMARK;
  return (
    <span className={`inline-flex items-center gap-[0.34em] text-[var(--certa-text)] ${className ?? ''}`} style={{ fontSize: height }} role="img" aria-label="Certa by Arkhon Industries">
      <CertaMark className="shrink-0" />
      <span className="flex flex-col justify-center leading-none" aria-hidden>
        <svg viewBox={`0 ${-w.capHeight - 1} ${w.width + 1} ${w.capHeight + 2}`} width={(w.width + 1) * k} height={(w.capHeight + 2) * k}>
          <path d={w.d} fill="currentColor" />
        </svg>
        {endorsed && (
          <span className="mt-[0.16em] text-[0.33em] font-medium whitespace-nowrap text-[var(--certa-muted)]" style={{ lineHeight: 1 }}>
            by Arkhon Industries
          </span>
        )}
      </span>
    </span>
  );
}
