'use client';

import { motion, useReducedMotion } from 'motion/react';
import { CERTA_MARK, CERTA_MARK_LINES, CERTA_MARK_SMALL, CERTA_WORDMARK, MARK_STROKE } from './brand-marks';

/**
 * Certa mark: one line — a check whose long arm rises to become the side of the Arkhon
 * triangle. Geometry is generated by brand/build.py (brand/README.md); don't redraw it here.
 * `small` uses the heavier-stroke variant meant for ≤ 24 px.
 */
export function CertaMark({ className, title, small }: { className?: string; title?: string; small?: boolean }) {
  const m = small ? CERTA_MARK_SMALL : CERTA_MARK;
  return (
    <svg viewBox={m.viewBox} width="1em" height="1em" className={className} role={title ? 'img' : undefined} aria-label={title} aria-hidden={title ? undefined : true}>
      <path d={m.d} fill="currentColor" />
    </svg>
  );
}

/** The mark drawing itself: the check, then up into the peak, down, and along the base. */
export function CertaMarkAnimated({ className, delay = 0.2, duration = 1.4 }: { className?: string; delay?: number; duration?: number }) {
  const reduce = useReducedMotion();
  if (reduce) return <CertaMark className={className} />;
  const [line] = CERTA_MARK_LINES;
  const d = 'M' + line!.map(([x, y]) => `${x} ${y}`).join(' L');
  return (
    <svg viewBox={CERTA_MARK.viewBox} width="1em" height="1em" className={className} aria-hidden>
      <motion.path
        d={d}
        fill="none"
        stroke="currentColor"
        strokeWidth={MARK_STROKE}
        strokeLinecap="round"
        strokeLinejoin="round"
        initial={{ pathLength: 0 }}
        animate={{ pathLength: 1 }}
        transition={{ duration, delay, ease: [0.65, 0, 0.35, 1] }}
      />
    </svg>
  );
}

/**
 * Lockup: mark + outlined Geist wordmark (identical on every device), optionally endorsed
 * "by Arkhon Industries". `height` is the mark height in px; everything scales from it.
 */
export function CertaLogo({ height = 28, endorsed = false, animated = false, className }: { height?: number; endorsed?: boolean; animated?: boolean; className?: string }) {
  const w = CERTA_WORDMARK;
  const k = (height * 0.66) / 40;
  const vbTop = -w.ascent - 1;
  const vbH = w.ascent + 0.3 * 40;
  return (
    <span className={`inline-flex items-center gap-[0.26em] text-[var(--certa-text)] ${className ?? ''}`} style={{ fontSize: height }} role="img" aria-label="certa by Arkhon Industries">
      {animated ? <CertaMarkAnimated className="shrink-0" /> : <CertaMark className="shrink-0" small={height <= 24} />}
      <span className="flex flex-col justify-center leading-none" aria-hidden>
        <svg viewBox={`0 ${vbTop} ${w.width + 1} ${vbH}`} width={(w.width + 1) * k} height={vbH * k} className="-mb-[0.06em]">
          <path d={w.d} fill="currentColor" />
        </svg>
        {endorsed && (
          <span className="mt-[0.06em] text-[0.3em] font-medium whitespace-nowrap text-[var(--certa-muted)]" style={{ lineHeight: 1 }}>
            by Arkhon Industries
          </span>
        )}
      </span>
    </span>
  );
}
