// GENERATED by `pnpm --filter @certa/contract gen:fixtures`. Do not edit by hand.
// "Today" in all fixtures is 2026-10-08 (America/Denver).
import type { AuthFixtures } from './scenario.ts';

export const auth = {
  "signIn": {
    "loading": false,
    "error": null,
    "initialEmail": null,
    "magicLinkSentTo": null,
    "ssoProviders": []
  },
  "signInMagicLinkSent": {
    "loading": false,
    "error": null,
    "initialEmail": "dana.reyes@example.com",
    "magicLinkSentTo": "dana.reyes@example.com",
    "ssoProviders": []
  },
  "signInError": {
    "loading": false,
    "error": "That email and password don’t match. Try again or use a sign-in link.",
    "initialEmail": "dana.reyes@example.com",
    "magicLinkSentTo": null,
    "ssoProviders": []
  },
  "signUp": {
    "loading": false,
    "error": null,
    "timezoneOptions": [
      {
        "value": "America/Denver",
        "label": "America/Denver"
      },
      {
        "value": "America/New_York",
        "label": "America/New York"
      },
      {
        "value": "America/Chicago",
        "label": "America/Chicago"
      },
      {
        "value": "America/Los_Angeles",
        "label": "America/Los Angeles"
      },
      {
        "value": "America/Phoenix",
        "label": "America/Phoenix"
      },
      {
        "value": "America/Anchorage",
        "label": "America/Anchorage"
      },
      {
        "value": "Pacific/Honolulu",
        "label": "Pacific/Honolulu"
      }
    ],
    "defaultTimezone": "America/Denver",
    "passwordMinLength": 12
  }
} satisfies AuthFixtures;
