// GENERATED by `pnpm --filter @certa/contract gen:fixtures`. Do not edit by hand.
// "Today" in all fixtures is 2026-10-08 (America/Denver).
import type { FixtureScenario } from './scenario.ts';

export const empty = {
  "id": "empty",
  "description": "Brand-new organization: no pilots, aircraft, batteries, or flights. Exercises every empty state.",
  "shell": {
    "user": {
      "id": "0199c4a0-0000-7000-8000-0000003d0902",
      "name": "Jordan Avery",
      "initials": "JA",
      "email": "jordan.avery@example.com",
      "roleLabel": "Owner"
    },
    "organization": {
      "id": "0199c4a0-0000-7000-8000-0000003d0901",
      "name": "New Horizon UAS"
    },
    "orgOptions": [
      {
        "orgId": "0199c4a0-0000-7000-8000-0000003d0901",
        "name": "New Horizon UAS",
        "role": "owner",
        "current": true
      }
    ],
    "navigation": [
      {
        "id": "today",
        "label": "Today",
        "href": "/",
        "icon": "today",
        "active": true,
        "badge": null
      },
      {
        "id": "flights",
        "label": "Flights",
        "href": "/flights",
        "icon": "flights",
        "active": false,
        "badge": null
      },
      {
        "id": "pilots",
        "label": "Pilots",
        "href": "/pilots",
        "icon": "pilots",
        "active": false,
        "badge": null
      },
      {
        "id": "aircraft",
        "label": "Aircraft",
        "href": "/aircraft",
        "icon": "aircraft",
        "active": false,
        "badge": null
      },
      {
        "id": "batteries",
        "label": "Batteries",
        "href": "/batteries",
        "icon": "batteries",
        "active": false,
        "badge": null
      },
      {
        "id": "rules",
        "label": "Rule pack",
        "href": "/admin/rules",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "members",
        "label": "Members",
        "href": "/admin/members",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "audit",
        "label": "Audit log",
        "href": "/admin/audit",
        "icon": "records",
        "active": false,
        "badge": null
      },
      {
        "id": "settings",
        "label": "Settings",
        "href": "/settings/organization",
        "icon": "settings",
        "active": false,
        "badge": null
      }
    ],
    "permissions": [
      "org.read",
      "org.update",
      "org.billing",
      "members.read",
      "members.manage",
      "rules.read",
      "rules.override",
      "audit.read",
      "pilots.read",
      "pilots.manage",
      "credentials.read",
      "credentials.manage",
      "aircraft.read",
      "aircraft.manage",
      "aircraft.ground",
      "aircraft.override_grounding",
      "batteries.read",
      "batteries.manage",
      "components.manage",
      "maintenance.read",
      "maintenance.manage",
      "flights.read",
      "flights.log",
      "flights.edit",
      "missions.read",
      "missions.manage",
      "checklists.read",
      "checklists.manage_templates",
      "checklists.run",
      "incidents.read",
      "incidents.report",
      "incidents.manage",
      "exports.create",
      "integrity.verify",
      "integrations.manage"
    ],
    "complianceNotice": "Certa is a record-keeping tool. Operators remain responsible for compliance with all applicable regulations. Regulatory values shown are pending verification.",
    "sync": {
      "status": "online",
      "pendingChanges": 0,
      "lastSynced": null,
      "message": null,
      "conflictCount": 0
    },
    "theme": "light"
  },
  "mobileShell": {
    "user": {
      "id": "0199c4a0-0000-7000-8000-0000003d0902",
      "name": "Jordan Avery",
      "initials": "JA",
      "email": "jordan.avery@example.com",
      "roleLabel": "Owner"
    },
    "organization": {
      "id": "0199c4a0-0000-7000-8000-0000003d0901",
      "name": "New Horizon UAS"
    },
    "orgOptions": [
      {
        "orgId": "0199c4a0-0000-7000-8000-0000003d0901",
        "name": "New Horizon UAS",
        "role": "owner",
        "current": true
      }
    ],
    "navigation": [
      {
        "id": "today",
        "label": "Today",
        "href": "/",
        "icon": "today",
        "active": true,
        "badge": null
      },
      {
        "id": "flights",
        "label": "Flights",
        "href": "/flights",
        "icon": "flights",
        "active": false,
        "badge": null
      },
      {
        "id": "pilots",
        "label": "Pilots",
        "href": "/pilots",
        "icon": "pilots",
        "active": false,
        "badge": null
      },
      {
        "id": "aircraft",
        "label": "Aircraft",
        "href": "/aircraft",
        "icon": "aircraft",
        "active": false,
        "badge": null
      },
      {
        "id": "batteries",
        "label": "Batteries",
        "href": "/batteries",
        "icon": "batteries",
        "active": false,
        "badge": null
      },
      {
        "id": "rules",
        "label": "Rule pack",
        "href": "/admin/rules",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "members",
        "label": "Members",
        "href": "/admin/members",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "audit",
        "label": "Audit log",
        "href": "/admin/audit",
        "icon": "records",
        "active": false,
        "badge": null
      },
      {
        "id": "settings",
        "label": "Settings",
        "href": "/settings/organization",
        "icon": "settings",
        "active": false,
        "badge": null
      }
    ],
    "permissions": [
      "org.read",
      "org.update",
      "org.billing",
      "members.read",
      "members.manage",
      "rules.read",
      "rules.override",
      "audit.read",
      "pilots.read",
      "pilots.manage",
      "credentials.read",
      "credentials.manage",
      "aircraft.read",
      "aircraft.manage",
      "aircraft.ground",
      "aircraft.override_grounding",
      "batteries.read",
      "batteries.manage",
      "components.manage",
      "maintenance.read",
      "maintenance.manage",
      "flights.read",
      "flights.log",
      "flights.edit",
      "missions.read",
      "missions.manage",
      "checklists.read",
      "checklists.manage_templates",
      "checklists.run",
      "incidents.read",
      "incidents.report",
      "incidents.manage",
      "exports.create",
      "integrity.verify",
      "integrations.manage"
    ],
    "complianceNotice": "Certa is a record-keeping tool. Operators remain responsible for compliance with all applicable regulations. Regulatory values shown are pending verification.",
    "sync": {
      "status": "online",
      "pendingChanges": 0,
      "lastSynced": {
        "iso": "2026-10-08T15:58:00.000Z",
        "absolute": "Oct 8, 2026, 9:58 AM MDT",
        "relative": "today",
        "display": "Oct 8, 2026, 9:58 AM MDT — today",
        "daysFromToday": 0
      },
      "message": null,
      "conflictCount": 0
    },
    "theme": "light"
  },
  "screens": {
    "readinessDashboard": {
      "loading": false,
      "error": null,
      "asOf": {
        "iso": "2026-10-08",
        "absolute": "Oct 8, 2026",
        "relative": "today",
        "display": "Oct 8, 2026 — today",
        "daysFromToday": 0
      },
      "overall": {
        "level": "green",
        "label": "Everyone is legal to fly"
      },
      "counts": {
        "green": 0,
        "amber": 0,
        "red": 0
      },
      "pilots": [],
      "aircraft": [],
      "upcoming": [],
      "empty": {
        "title": "Add your first pilot and aircraft",
        "body": "Certa tracks certificates, registrations, and maintenance so you know who and what is legal to fly today.",
        "actionLabel": "Add aircraft"
      }
    },
    "pilotList": {
      "loading": false,
      "error": null,
      "pilots": [],
      "search": "",
      "canManage": true,
      "empty": {
        "title": "No pilots yet",
        "body": "Add pilots to track their certificates, recurrent training, and flight time.",
        "actionLabel": "Add pilot"
      }
    },
    "pilotDetail": {
      "loading": false,
      "error": null,
      "pilot": null,
      "credentials": [],
      "recentFlights": [],
      "credentialTypeOptions": [
        {
          "value": "part107_certificate",
          "label": "Remote Pilot Certificate (Part 107)",
          "expires": false
        },
        {
          "value": "part107_initial_knowledge",
          "label": "Initial aeronautical knowledge test",
          "expires": true
        },
        {
          "value": "part107_recurrent",
          "label": "Recurrent training (Part 107)",
          "expires": true
        },
        {
          "value": "night_operations_training",
          "label": "Night operations training",
          "expires": false
        },
        {
          "value": "type_specific_training",
          "label": "Type-specific training",
          "expires": false
        },
        {
          "value": "waiver_held",
          "label": "Waiver / certificate of waiver (pilot-held)",
          "expires": false
        }
      ],
      "canEdit": true
    },
    "aircraftList": {
      "loading": false,
      "error": null,
      "aircraft": [],
      "search": "",
      "statusFilter": "all",
      "canManage": true,
      "empty": {
        "title": "No aircraft yet",
        "body": "Add an aircraft to track its registration, Remote ID, flight hours, and maintenance.",
        "actionLabel": "Add aircraft"
      }
    },
    "aircraftDetail": {
      "loading": false,
      "error": null,
      "aircraft": null,
      "recentFlights": [],
      "batteries": [],
      "canEdit": true,
      "canGround": true
    },
    "batteryList": {
      "loading": false,
      "error": null,
      "batteries": [],
      "canManage": true,
      "empty": {
        "title": "No batteries yet",
        "body": "Add batteries to track cycle counts automatically from your flights and get retirement warnings.",
        "actionLabel": "Add battery"
      }
    },
    "flightList": {
      "loading": false,
      "error": null,
      "flights": {
        "items": [],
        "total": 0,
        "nextCursor": null
      },
      "filter": {
        "pilotId": null,
        "aircraftId": null,
        "from": null,
        "to": null
      },
      "pilotOptions": [],
      "aircraftOptions": [],
      "totals": {
        "flights": 0,
        "flightTime": {
          "value": 0,
          "unit": "s",
          "display": "0m 00s"
        }
      },
      "canLog": true,
      "empty": {
        "title": "No flights logged",
        "body": "Log a flight in seconds, or import logs from your flight controller to fill your logbook automatically.",
        "actionLabel": "Log a flight"
      }
    },
    "flightDetail": {
      "loading": false,
      "error": null,
      "flight": null,
      "path": null,
      "altitudeProfile": [],
      "canEdit": true
    },
    "logFlight": {
      "loading": false,
      "error": null,
      "defaults": {
        "pilotId": "",
        "aircraftId": null,
        "batteryIds": [],
        "siteId": null,
        "operationType": "commercial",
        "takeoffAt": "2026-10-08T15:30:00.000Z",
        "durationMinutes": null
      },
      "hasLastFlight": false,
      "pilotOptions": [],
      "aircraftOptions": [],
      "batteryOptions": [],
      "siteOptions": [
        {
          "value": "site-1",
          "label": "Henderson Solar Farm",
          "recent": true
        },
        {
          "value": "site-2",
          "label": "Cherry Creek Bridge",
          "recent": true
        },
        {
          "value": "site-3",
          "label": "Riverside Substation",
          "recent": false
        },
        {
          "value": "site-4",
          "label": "Lakewood Water Tower",
          "recent": false
        },
        {
          "value": "site-5",
          "label": "Golden Rooftop Survey",
          "recent": false
        }
      ],
      "operationTypeOptions": [
        {
          "value": "commercial",
          "label": "Commercial (Part 107)"
        },
        {
          "value": "training",
          "label": "Training"
        },
        {
          "value": "public_safety",
          "label": "Public safety"
        },
        {
          "value": "maintenance_test",
          "label": "Maintenance test flight"
        },
        {
          "value": "other",
          "label": "Other"
        }
      ],
      "warnings": [],
      "altitudeUnitLabel": "ft",
      "fieldErrors": {},
      "saving": false
    },
    "rulePackAdmin": {
      "loading": false,
      "error": null,
      "pack": {
        "jurisdiction": "US-FAA-Part107",
        "name": "United States — FAA 14 CFR Part 107 (Small UAS)",
        "version": "1.0.0",
        "authority": "Federal Aviation Administration",
        "effectiveFrom": {
          "iso": "2021-04-21",
          "absolute": "Apr 21, 2021",
          "relative": "5.5 years ago",
          "display": "Apr 21, 2021 — 5.5 years ago",
          "daysFromToday": -1996
        },
        "disclaimer": "Values in this pack are provided for record-keeping convenience and are pending verification. Certa does not provide legal or regulatory advice; operators remain responsible for compliance with all applicable regulations.",
        "ruleCount": 19,
        "unverifiedCount": 19
      },
      "availableJurisdictions": [
        {
          "jurisdiction": "US-FAA-Part107",
          "name": "United States — FAA 14 CFR Part 107 (Small UAS)",
          "active": true
        }
      ],
      "credentialTypes": [
        {
          "id": "part107_certificate",
          "label": "Remote Pilot Certificate (Part 107)",
          "description": "Remote pilot certificate with small UAS rating. The certificate itself has no expiration date; currency is maintained through recurrent training or testing.",
          "validity": "Does not expire",
          "requiredForCurrency": true
        },
        {
          "id": "part107_initial_knowledge",
          "label": "Initial aeronautical knowledge test",
          "description": "Passing the initial knowledge test establishes currency for the recurrent period.",
          "validity": "24 calendar months (14 CFR 107.65)",
          "requiredForCurrency": false
        },
        {
          "id": "part107_recurrent",
          "label": "Recurrent training (Part 107)",
          "description": "Online recurrent training (or recurrent test) completed within the recency window required to exercise the privileges of the remote pilot certificate.",
          "validity": "24 calendar months (14 CFR 107.65)",
          "requiredForCurrency": true
        },
        {
          "id": "night_operations_training",
          "label": "Night operations training",
          "description": "Training or testing covering night operations, required before conducting operations at night. Satisfied by recurrent training/testing completed after the night-rule effective date.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        },
        {
          "id": "type_specific_training",
          "label": "Type-specific training",
          "description": "Manufacturer or operator training for a specific aircraft type. Expiry set per record.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        },
        {
          "id": "waiver_held",
          "label": "Waiver / certificate of waiver (pilot-held)",
          "description": "A Part 107 waiver issued to the pilot. Expiry is taken from the waiver document.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        }
      ],
      "rules": [
        {
          "id": "pilot.aeronautical_knowledge.recency",
          "title": "Aeronautical knowledge recency",
          "description": "A remote pilot must have completed initial or recurrent aeronautical knowledge training or testing within the preceding period to act as remote pilot in command.",
          "appliesTo": "pilot",
          "valueDisplay": "24 months (calendar)",
          "packValueDisplay": null,
          "statedAs": "24 calendar months",
          "sourceCitation": "14 CFR 107.65",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-C/section-107.65",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "pilot.minimum_age",
          "title": "Minimum age for remote pilot certificate",
          "description": "Minimum age to be eligible for a remote pilot certificate.",
          "appliesTo": "pilot",
          "valueDisplay": "16",
          "packValueDisplay": null,
          "statedAs": "16 years of age",
          "sourceCitation": "14 CFR 107.61(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-C/section-107.61",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "integer"
        },
        {
          "id": "pilot.night_operations.training_required",
          "title": "Night operations require training",
          "description": "Operations at night require the remote pilot to have completed training or testing that covers night operations.",
          "appliesTo": "pilot",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.29(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.29",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "aircraft.registration.validity",
          "title": "Aircraft registration validity period",
          "description": "Period for which a small unmanned aircraft registration remains valid before renewal.",
          "appliesTo": "aircraft",
          "valueDisplay": "3 years",
          "packValueDisplay": null,
          "statedAs": "3 years",
          "sourceCitation": "14 CFR 48.100",
          "sourceTitle": "14 CFR Part 48",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-C/part-48",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "aircraft.max_takeoff_mass",
          "title": "Maximum takeoff mass for a small UAS",
          "description": "A small unmanned aircraft must weigh less than this value at takeoff, including everything on board or otherwise attached.",
          "appliesTo": "aircraft",
          "valueDisplay": "55 lb",
          "packValueDisplay": null,
          "statedAs": "less than 55 pounds",
          "sourceCitation": "14 CFR 107.3 (definition of small unmanned aircraft)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.3",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "mass"
        },
        {
          "id": "aircraft.registration.min_mass",
          "title": "Registration mass threshold",
          "description": "Mass above which registration is required for aircraft operated recreationally. Under Part 107 every aircraft must be registered regardless of mass (see aircraft.registration.required_part107).",
          "appliesTo": "aircraft",
          "valueDisplay": "0.55 lb",
          "packValueDisplay": null,
          "statedAs": "more than 0.55 pounds (250 grams)",
          "sourceCitation": "14 CFR 48.15",
          "sourceTitle": "14 CFR Part 48",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-C/part-48",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "mass"
        },
        {
          "id": "aircraft.registration.required_part107",
          "title": "Registration required for all Part 107 aircraft",
          "description": "Aircraft operated under Part 107 must be registered regardless of mass.",
          "appliesTo": "aircraft",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.13",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.13",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "aircraft.remote_id.required",
          "title": "Remote ID required",
          "description": "Aircraft must comply with Remote ID by standard Remote ID, a broadcast module, or by operating within an FAA-recognized identification area (FRIA).",
          "appliesTo": "aircraft",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 89.105",
          "sourceTitle": "14 CFR Part 89",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-89",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "operation.max_altitude_agl",
          "title": "Maximum altitude above ground level",
          "description": "Maximum altitude above ground level, unless flown within a 400-foot radius of a structure and not higher than 400 feet above the structure's immediate uppermost limit.",
          "appliesTo": "operation",
          "valueDisplay": "400 ft (121.9 m)",
          "packValueDisplay": null,
          "statedAs": "400 feet AGL",
          "sourceCitation": "14 CFR 107.51(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.max_groundspeed",
          "title": "Maximum groundspeed",
          "description": "Maximum groundspeed of the small unmanned aircraft.",
          "appliesTo": "operation",
          "valueDisplay": "100 mph",
          "packValueDisplay": null,
          "statedAs": "87 knots (100 miles per hour)",
          "sourceCitation": "14 CFR 107.51(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "speed"
        },
        {
          "id": "operation.min_flight_visibility",
          "title": "Minimum flight visibility",
          "description": "Minimum flight visibility from the control station.",
          "appliesTo": "operation",
          "valueDisplay": "15,840 ft (4,828 m)",
          "packValueDisplay": null,
          "statedAs": "3 statute miles",
          "sourceCitation": "14 CFR 107.51(c)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.cloud_clearance_below",
          "title": "Minimum distance below clouds",
          "description": "Minimum vertical distance below clouds.",
          "appliesTo": "operation",
          "valueDisplay": "500 ft (152.4 m)",
          "packValueDisplay": null,
          "statedAs": "500 feet below the cloud",
          "sourceCitation": "14 CFR 107.51(d)(1)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.cloud_clearance_horizontal",
          "title": "Minimum horizontal distance from clouds",
          "description": "Minimum horizontal distance from clouds.",
          "appliesTo": "operation",
          "valueDisplay": "2,000 ft (609.6 m)",
          "packValueDisplay": null,
          "statedAs": "2,000 feet horizontally from the cloud",
          "sourceCitation": "14 CFR 107.51(d)(2)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.night_anticollision_lighting_visibility",
          "title": "Anti-collision lighting visibility (night / civil twilight)",
          "description": "Operations at night or during civil twilight require anti-collision lighting visible for at least this distance.",
          "appliesTo": "operation",
          "valueDisplay": "15,840 ft (4,828 m)",
          "packValueDisplay": null,
          "statedAs": "3 statute miles",
          "sourceCitation": "14 CFR 107.29(a)(2), 107.29(c)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.29",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.remote_id.enforcement_date",
          "title": "Remote ID operating requirement date",
          "description": "Date from which operators must comply with Remote ID operating requirements.",
          "appliesTo": "operation",
          "valueDisplay": "Sep 16, 2023",
          "packValueDisplay": null,
          "statedAs": "September 16, 2023 (FAA exercised enforcement discretion until March 16, 2024)",
          "sourceCitation": "14 CFR 89.105; FAA enforcement policy statement",
          "sourceTitle": "14 CFR Part 89",
          "sourceUrl": "https://www.faa.gov/uas/getting_started/remote_id",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "date"
        },
        {
          "id": "incident.report.deadline",
          "title": "Accident reporting deadline",
          "description": "Time after an accident within which the remote pilot in command must report it to the FAA when it meets a reporting threshold.",
          "appliesTo": "incident",
          "valueDisplay": "10 days",
          "packValueDisplay": null,
          "statedAs": "within 10 calendar days",
          "sourceCitation": "14 CFR 107.9",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "incident.report.injury_min_ais_level",
          "title": "Reportable injury threshold (AIS)",
          "description": "An accident causing serious injury to any person is reportable. Modelled as an injury of at least this level on the Abbreviated Injury Scale.",
          "appliesTo": "incident",
          "valueDisplay": "3",
          "packValueDisplay": null,
          "statedAs": "Serious injury — AIS level 3 or higher",
          "sourceCitation": "14 CFR 107.9(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "integer"
        },
        {
          "id": "incident.report.loss_of_consciousness",
          "title": "Loss of consciousness is reportable",
          "description": "An accident causing any loss of consciousness is reportable.",
          "appliesTo": "incident",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.9(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "incident.report.property_damage_min",
          "title": "Reportable property damage threshold",
          "description": "Damage to any property, other than the small unmanned aircraft, is reportable when the cost of repair (including materials and labor) or fair market value in the event of total loss exceeds this amount.",
          "appliesTo": "incident",
          "valueDisplay": "500.00 USD",
          "packValueDisplay": null,
          "statedAs": "greater than $500",
          "sourceCitation": "14 CFR 107.9(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "money"
        }
      ],
      "filter": {
        "search": "",
        "appliesTo": null,
        "unverifiedOnly": false
      },
      "empty": {
        "title": "No rules match",
        "body": "Try clearing the search or filters.",
        "actionLabel": null
      }
    },
    "membersAdmin": {
      "loading": false,
      "error": null,
      "members": [
        {
          "membershipId": "0199c4a0-0000-7000-8000-0000003d0903",
          "user": {
            "id": "0199c4a0-0000-7000-8000-0000003d0902",
            "name": "Jordan Avery",
            "initials": "JA"
          },
          "email": "jordan.avery@example.com",
          "role": "owner",
          "roleLabel": "Owner",
          "expires": null,
          "joined": {
            "iso": "2026-10-08T15:55:00.000Z",
            "absolute": "Oct 8, 2026, 9:55 AM MDT",
            "relative": "today",
            "display": "Oct 8, 2026, 9:55 AM MDT — today",
            "daysFromToday": 0
          },
          "isSelf": true
        }
      ],
      "roleOptions": [
        {
          "value": "owner",
          "label": "Owner",
          "description": "Everything, including billing and rule-pack overrides."
        },
        {
          "value": "admin",
          "label": "Admin",
          "description": "Everything except billing."
        },
        {
          "value": "chief_pilot",
          "label": "Chief Pilot",
          "description": "Manage pilots, missions, checklists, and approvals."
        },
        {
          "value": "pilot",
          "label": "Pilot",
          "description": "Log own flights, run checklists, report incidents, view assigned missions."
        },
        {
          "value": "maintenance_tech",
          "label": "Maintenance Tech",
          "description": "Maintenance events, components, batteries, and grounding."
        },
        {
          "value": "viewer",
          "label": "Viewer",
          "description": "Read-only access."
        },
        {
          "value": "auditor",
          "label": "Auditor",
          "description": "Time-boxed, read-only access to a defined scope. Every view is logged."
        }
      ],
      "canManage": true,
      "empty": {
        "title": "Just you so far",
        "body": "Invite pilots, maintenance techs, or an auditor. Each person gets a sign-in link by email.",
        "actionLabel": "Invite someone"
      }
    },
    "orgSettings": {
      "loading": false,
      "error": null,
      "values": {
        "name": "New Horizon UAS",
        "timezone": "America/Denver",
        "units": {
          "length": "ft",
          "speed": "mph",
          "mass": "lb",
          "temperature": "F"
        },
        "defaultJurisdiction": "US-FAA-Part107"
      },
      "options": {
        "timezones": [
          {
            "value": "America/Denver",
            "label": "America/Denver"
          },
          {
            "value": "America/New_York",
            "label": "America/New York"
          },
          {
            "value": "America/Chicago",
            "label": "America/Chicago"
          },
          {
            "value": "America/Los_Angeles",
            "label": "America/Los Angeles"
          },
          {
            "value": "America/Phoenix",
            "label": "America/Phoenix"
          },
          {
            "value": "America/Anchorage",
            "label": "America/Anchorage"
          },
          {
            "value": "Pacific/Honolulu",
            "label": "Pacific/Honolulu"
          },
          {
            "value": "UTC",
            "label": "UTC"
          }
        ],
        "length": [
          {
            "value": "ft",
            "label": "Feet"
          },
          {
            "value": "m",
            "label": "Metres"
          }
        ],
        "speed": [
          {
            "value": "mph",
            "label": "mph"
          },
          {
            "value": "kph",
            "label": "km/h"
          },
          {
            "value": "kt",
            "label": "Knots"
          },
          {
            "value": "mps",
            "label": "m/s"
          }
        ],
        "mass": [
          {
            "value": "lb",
            "label": "Pounds"
          },
          {
            "value": "kg",
            "label": "Kilograms"
          },
          {
            "value": "g",
            "label": "Grams"
          }
        ],
        "temperature": [
          {
            "value": "F",
            "label": "°F"
          },
          {
            "value": "C",
            "label": "°C"
          }
        ],
        "jurisdictions": [
          {
            "value": "US-FAA-Part107",
            "label": "United States — FAA Part 107"
          }
        ]
      },
      "canEdit": true,
      "saving": false
    },
    "auditLog": {
      "loading": false,
      "error": null,
      "events": [],
      "hasMore": false,
      "filter": {
        "entity": null,
        "actorUserId": null
      },
      "entityOptions": [
        {
          "value": "flights",
          "label": "Flights"
        },
        {
          "value": "aircraft",
          "label": "Aircraft"
        },
        {
          "value": "pilots",
          "label": "Pilots"
        },
        {
          "value": "credentials",
          "label": "Credentials"
        },
        {
          "value": "org_rule_overrides",
          "label": "Rule overrides"
        },
        {
          "value": "memberships",
          "label": "Members"
        }
      ],
      "empty": {
        "title": "No changes recorded yet",
        "body": "Every change to your records will appear here with who made it and what changed.",
        "actionLabel": null
      }
    },
    "syncConflicts": {
      "loading": false,
      "error": null,
      "conflicts": [],
      "empty": {
        "title": "Everything is in sync",
        "body": "Changes made offline sync automatically. Anything that needs a decision will appear here.",
        "actionLabel": null
      }
    }
  }
} satisfies FixtureScenario;
