// GENERATED by `pnpm --filter @certa/contract gen:fixtures`. Do not edit by hand.
// "Today" in all fixtures is 2026-10-08 (America/Denver).
import type { FixtureScenario } from './scenario.ts';

export const longNames = {
  "id": "longNames",
  "description": "Very long names everywhere: organization, pilots, aircraft nicknames, and locations.",
  "shell": {
    "basePath": "/certa",
    "user": {
      "id": "0199c4a0-0000-7000-8000-0000004c4b42",
      "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
      "initials": "MI",
      "email": "maximilian.alexander.featherstonehaugh.montgomery.iii@example.com",
      "roleLabel": "Owner"
    },
    "organization": {
      "id": "0199c4a0-0000-7000-8000-0000004c4b41",
      "name": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program"
    },
    "orgOptions": [
      {
        "orgId": "0199c4a0-0000-7000-8000-0000004c4b41",
        "name": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program",
        "role": "owner",
        "current": true
      }
    ],
    "navigation": [
      {
        "id": "today",
        "label": "Today",
        "href": "/",
        "icon": "today",
        "active": true,
        "badge": null
      },
      {
        "id": "flights",
        "label": "Flights",
        "href": "/flights",
        "icon": "flights",
        "active": false,
        "badge": null
      },
      {
        "id": "pilots",
        "label": "Pilots",
        "href": "/pilots",
        "icon": "pilots",
        "active": false,
        "badge": null
      },
      {
        "id": "aircraft",
        "label": "Aircraft",
        "href": "/aircraft",
        "icon": "aircraft",
        "active": false,
        "badge": null
      },
      {
        "id": "batteries",
        "label": "Batteries",
        "href": "/batteries",
        "icon": "batteries",
        "active": false,
        "badge": null
      },
      {
        "id": "rules",
        "label": "Rule pack",
        "href": "/admin/rules",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "members",
        "label": "Members",
        "href": "/admin/members",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "audit",
        "label": "Audit log",
        "href": "/admin/audit",
        "icon": "records",
        "active": false,
        "badge": null
      },
      {
        "id": "settings",
        "label": "Settings",
        "href": "/settings/organization",
        "icon": "settings",
        "active": false,
        "badge": null
      }
    ],
    "permissions": [
      "org.read",
      "org.update",
      "org.billing",
      "members.read",
      "members.manage",
      "rules.read",
      "rules.override",
      "audit.read",
      "pilots.read",
      "pilots.manage",
      "credentials.read",
      "credentials.manage",
      "aircraft.read",
      "aircraft.manage",
      "aircraft.ground",
      "aircraft.override_grounding",
      "batteries.read",
      "batteries.manage",
      "components.manage",
      "maintenance.read",
      "maintenance.manage",
      "flights.read",
      "flights.log",
      "flights.edit",
      "missions.read",
      "missions.manage",
      "checklists.read",
      "checklists.manage_templates",
      "checklists.run",
      "incidents.read",
      "incidents.report",
      "incidents.manage",
      "exports.create",
      "integrity.verify",
      "integrations.manage"
    ],
    "complianceNotice": "Certa is a record-keeping tool. Operators remain responsible for compliance with all applicable regulations. Regulatory values shown are pending verification.",
    "sync": {
      "status": "online",
      "pendingChanges": 0,
      "lastSynced": null,
      "message": null,
      "conflictCount": 0
    },
    "theme": "light"
  },
  "fieldShell": {
    "basePath": "/certa",
    "user": {
      "id": "0199c4a0-0000-7000-8000-0000004c4b42",
      "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
      "initials": "MI",
      "email": "maximilian.alexander.featherstonehaugh.montgomery.iii@example.com",
      "roleLabel": "Owner"
    },
    "organization": {
      "id": "0199c4a0-0000-7000-8000-0000004c4b41",
      "name": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program"
    },
    "orgOptions": [
      {
        "orgId": "0199c4a0-0000-7000-8000-0000004c4b41",
        "name": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program",
        "role": "owner",
        "current": true
      }
    ],
    "navigation": [
      {
        "id": "today",
        "label": "Today",
        "href": "/",
        "icon": "today",
        "active": true,
        "badge": null
      },
      {
        "id": "flights",
        "label": "Flights",
        "href": "/flights",
        "icon": "flights",
        "active": false,
        "badge": null
      },
      {
        "id": "pilots",
        "label": "Pilots",
        "href": "/pilots",
        "icon": "pilots",
        "active": false,
        "badge": null
      },
      {
        "id": "aircraft",
        "label": "Aircraft",
        "href": "/aircraft",
        "icon": "aircraft",
        "active": false,
        "badge": null
      },
      {
        "id": "batteries",
        "label": "Batteries",
        "href": "/batteries",
        "icon": "batteries",
        "active": false,
        "badge": null
      },
      {
        "id": "rules",
        "label": "Rule pack",
        "href": "/admin/rules",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "members",
        "label": "Members",
        "href": "/admin/members",
        "icon": "admin",
        "active": false,
        "badge": null
      },
      {
        "id": "audit",
        "label": "Audit log",
        "href": "/admin/audit",
        "icon": "records",
        "active": false,
        "badge": null
      },
      {
        "id": "settings",
        "label": "Settings",
        "href": "/settings/organization",
        "icon": "settings",
        "active": false,
        "badge": null
      }
    ],
    "permissions": [
      "org.read",
      "org.update",
      "org.billing",
      "members.read",
      "members.manage",
      "rules.read",
      "rules.override",
      "audit.read",
      "pilots.read",
      "pilots.manage",
      "credentials.read",
      "credentials.manage",
      "aircraft.read",
      "aircraft.manage",
      "aircraft.ground",
      "aircraft.override_grounding",
      "batteries.read",
      "batteries.manage",
      "components.manage",
      "maintenance.read",
      "maintenance.manage",
      "flights.read",
      "flights.log",
      "flights.edit",
      "missions.read",
      "missions.manage",
      "checklists.read",
      "checklists.manage_templates",
      "checklists.run",
      "incidents.read",
      "incidents.report",
      "incidents.manage",
      "exports.create",
      "integrity.verify",
      "integrations.manage"
    ],
    "complianceNotice": "Certa is a record-keeping tool. Operators remain responsible for compliance with all applicable regulations. Regulatory values shown are pending verification.",
    "sync": {
      "status": "online",
      "pendingChanges": 0,
      "lastSynced": {
        "iso": "2026-10-08T15:58:00.000Z",
        "absolute": "Oct 8, 2026, 9:58 AM MDT",
        "relative": "today",
        "display": "Oct 8, 2026, 9:58 AM MDT — today",
        "daysFromToday": 0
      },
      "message": null,
      "conflictCount": 0
    },
    "theme": "light"
  },
  "screens": {
    "readinessDashboard": {
      "loading": false,
      "error": null,
      "asOf": {
        "iso": "2026-10-08",
        "absolute": "Oct 8, 2026",
        "relative": "today",
        "display": "Oct 8, 2026 — today",
        "daysFromToday": 0
      },
      "overall": {
        "level": "red",
        "label": "Some pilots or aircraft are not legal to fly"
      },
      "counts": {
        "green": 4,
        "amber": 1,
        "red": 1
      },
      "pilots": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b44",
          "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "subtitle": "Cert. 4720796",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "reasons": [],
          "href": "/pilots/0199c4a0-0000-7000-8000-0000004c4b44"
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b4b",
          "name": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
          "subtitle": "Cert. 4297786",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "reasons": [],
          "href": "/pilots/0199c4a0-0000-7000-8000-0000004c4b4b"
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b51",
          "name": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "subtitle": "Cert. 4176623",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "reasons": [],
          "href": "/pilots/0199c4a0-0000-7000-8000-0000004c4b51"
        }
      ],
      "aircraft": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b55",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "subtitle": "Reg. FA3XXX1179",
          "status": {
            "level": "green",
            "label": "Airworthy"
          },
          "reasons": [],
          "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b55"
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b58",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration",
          "subtitle": "Reg. FA3XXX11YE",
          "status": {
            "level": "red",
            "label": "Grounded"
          },
          "reasons": [
            {
              "level": "red",
              "text": "Grounded: Gimbal damage after hard landing — incident open",
              "due": null,
              "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b58"
            }
          ],
          "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b58"
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5b",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "subtitle": "Reg. FA3XXX12PJ",
          "status": {
            "level": "amber",
            "label": "Expires in 19 days"
          },
          "reasons": [
            {
              "level": "amber",
              "text": "Registration due soon",
              "due": {
                "iso": "2026-10-27",
                "absolute": "Oct 27, 2026",
                "relative": "in 19 days",
                "display": "Oct 27, 2026 — in 19 days",
                "daysFromToday": 19
              },
              "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b5b"
            }
          ],
          "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b5b"
        }
      ],
      "upcoming": [
        {
          "label": "Registration",
          "subject": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "due": {
            "iso": "2026-10-27",
            "absolute": "Oct 27, 2026",
            "relative": "in 19 days",
            "display": "Oct 27, 2026 — in 19 days",
            "daysFromToday": 19
          },
          "level": "amber",
          "href": "/aircraft/0199c4a0-0000-7000-8000-0000004c4b5b"
        },
        {
          "label": "Recurrent training (Part 107)",
          "subject": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "due": {
            "iso": "2026-11-30",
            "absolute": "Nov 30, 2026",
            "relative": "in 53 days",
            "display": "Nov 30, 2026 — in 53 days",
            "daysFromToday": 53
          },
          "level": "green",
          "href": "/pilots/0199c4a0-0000-7000-8000-0000004c4b51"
        }
      ],
      "empty": {
        "title": "Add your first pilot and aircraft",
        "body": "Certa tracks certificates, registrations, and maintenance so you know who and what is legal to fly today.",
        "actionLabel": "Add aircraft"
      }
    },
    "pilotList": {
      "loading": false,
      "error": null,
      "pilots": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b44",
          "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "certificateNumber": "4720796",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "totalFlightTime": {
            "value": 3226,
            "unit": "s",
            "display": "53m 46s"
          },
          "lastFlight": {
            "iso": "2026-10-06T14:27:00.000Z",
            "absolute": "Oct 6, 2026, 8:27 AM MDT",
            "relative": "2 days ago",
            "display": "Oct 6, 2026, 8:27 AM MDT — 2 days ago",
            "daysFromToday": -2
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b4b",
          "name": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
          "certificateNumber": "4297786",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "totalFlightTime": {
            "value": 3076,
            "unit": "s",
            "display": "51m 16s"
          },
          "lastFlight": {
            "iso": "2026-08-21T16:24:00.000Z",
            "absolute": "Aug 21, 2026, 10:24 AM MDT",
            "relative": "48 days ago",
            "display": "Aug 21, 2026, 10:24 AM MDT — 48 days ago",
            "daysFromToday": -48
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b51",
          "name": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "certificateNumber": "4176623",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "totalFlightTime": {
            "value": 4227,
            "unit": "s",
            "display": "1h 10m"
          },
          "lastFlight": {
            "iso": "2026-07-08T14:55:00.000Z",
            "absolute": "Jul 8, 2026, 8:55 AM MDT",
            "relative": "3 months ago",
            "display": "Jul 8, 2026, 8:55 AM MDT — 3 months ago",
            "daysFromToday": -92
          }
        }
      ],
      "search": "",
      "canManage": true,
      "empty": {
        "title": "No pilots yet",
        "body": "Add pilots to track their certificates, recurrent training, and flight time.",
        "actionLabel": "Add pilot"
      }
    },
    "pilotDetail": {
      "loading": false,
      "error": null,
      "pilot": {
        "id": "0199c4a0-0000-7000-8000-0000004c4b44",
        "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
        "email": "maximilian.alexander.featherstonehaugh.montgomery.iii@example.com",
        "phone": null,
        "certificateNumber": "4720796",
        "status": {
          "level": "green",
          "label": "Current"
        },
        "reasons": [],
        "totals": {
          "flights": 5,
          "flightTime": {
            "value": 3226,
            "unit": "s",
            "display": "53m 46s"
          },
          "last90DaysFlights": 1
        }
      },
      "credentials": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b45",
          "typeLabel": "Remote Pilot Certificate (Part 107)",
          "identifier": "4720796",
          "issued": {
            "iso": "2022-08-03",
            "absolute": "Aug 3, 2022",
            "relative": "4.2 years ago",
            "display": "Aug 3, 2022 — 4.2 years ago",
            "daysFromToday": -1527
          },
          "expires": null,
          "expiryBasis": "Does not expire",
          "status": {
            "level": "green",
            "label": "No expiry"
          },
          "documentCount": 1
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b47",
          "typeLabel": "Recurrent training (Part 107)",
          "identifier": null,
          "issued": {
            "iso": "2026-06-10",
            "absolute": "Jun 10, 2026",
            "relative": "4 months ago",
            "display": "Jun 10, 2026 — 4 months ago",
            "daysFromToday": -120
          },
          "expires": {
            "iso": "2028-06-30",
            "absolute": "Jun 30, 2028",
            "relative": "in 21 months",
            "display": "Jun 30, 2028 — in 21 months",
            "daysFromToday": 631
          },
          "expiryBasis": "Computed from issue date per 14 CFR 107.65",
          "status": {
            "level": "green",
            "label": "Current"
          },
          "documentCount": 0
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b48",
          "typeLabel": "Night operations training",
          "identifier": null,
          "issued": {
            "iso": "2026-06-10",
            "absolute": "Jun 10, 2026",
            "relative": "4 months ago",
            "display": "Jun 10, 2026 — 4 months ago",
            "daysFromToday": -120
          },
          "expires": null,
          "expiryBasis": "Does not expire",
          "status": {
            "level": "green",
            "label": "No expiry"
          },
          "documentCount": 0
        }
      ],
      "recentFlights": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5e",
          "takeoff": {
            "iso": "2026-10-06T14:27:00.000Z",
            "absolute": "Oct 6, 2026, 8:27 AM MDT",
            "relative": "2 days ago",
            "display": "Oct 6, 2026, 8:27 AM MDT — 2 days ago",
            "daysFromToday": -2
          },
          "duration": {
            "value": 750,
            "unit": "s",
            "display": "12m 30s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 135,
            "unit": "ft",
            "display": "135 ft"
          },
          "source": "manual",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b62",
          "takeoff": {
            "iso": "2026-04-10T16:46:00.000Z",
            "absolute": "Apr 10, 2026, 10:46 AM MDT",
            "relative": "6 months ago",
            "display": "Apr 10, 2026, 10:46 AM MDT — 6 months ago",
            "daysFromToday": -181
          },
          "duration": {
            "value": 507,
            "unit": "s",
            "display": "8m 27s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 305,
            "unit": "ft",
            "display": "305 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b65",
          "takeoff": {
            "iso": "2025-11-25T21:46:00.000Z",
            "absolute": "Nov 25, 2025, 2:46 PM MST",
            "relative": "10 months ago",
            "display": "Nov 25, 2025, 2:46 PM MST — 10 months ago",
            "daysFromToday": -317
          },
          "duration": {
            "value": 725,
            "unit": "s",
            "display": "12m 05s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Henderson Solar Farm — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 180,
            "unit": "ft",
            "display": "180 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b66",
          "takeoff": {
            "iso": "2025-10-12T21:16:00.000Z",
            "absolute": "Oct 12, 2025, 3:16 PM MDT",
            "relative": "12 months ago",
            "display": "Oct 12, 2025, 3:16 PM MDT — 12 months ago",
            "daysFromToday": -361
          },
          "duration": {
            "value": 740,
            "unit": "s",
            "display": "12m 20s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "locationName": "Boulder Creek Levee — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 276,
            "unit": "ft",
            "display": "276 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b68",
          "takeoff": {
            "iso": "2025-07-13T20:07:00.000Z",
            "absolute": "Jul 13, 2025, 2:07 PM MDT",
            "relative": "15 months ago",
            "display": "Jul 13, 2025, 2:07 PM MDT — 15 months ago",
            "daysFromToday": -452
          },
          "duration": {
            "value": 504,
            "unit": "s",
            "display": "8m 24s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "locationName": "Golden Rooftop Survey — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 279,
            "unit": "ft",
            "display": "279 ft"
          },
          "source": "import",
          "pendingSync": false
        }
      ],
      "credentialTypeOptions": [
        {
          "value": "part107_certificate",
          "label": "Remote Pilot Certificate (Part 107)",
          "expires": false
        },
        {
          "value": "part107_initial_knowledge",
          "label": "Initial aeronautical knowledge test",
          "expires": true
        },
        {
          "value": "part107_recurrent",
          "label": "Recurrent training (Part 107)",
          "expires": true
        },
        {
          "value": "night_operations_training",
          "label": "Night operations training",
          "expires": false
        },
        {
          "value": "type_specific_training",
          "label": "Type-specific training",
          "expires": false
        },
        {
          "value": "waiver_held",
          "label": "Waiver / certificate of waiver (pilot-held)",
          "expires": false
        }
      ],
      "canEdit": true
    },
    "aircraftList": {
      "loading": false,
      "error": null,
      "aircraft": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b55",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "makeModel": "DJI Mavic 3 Enterprise",
          "serialNumber": "DJ17X10000",
          "registrationNumber": "FA3XXX1179",
          "status": {
            "level": "green",
            "label": "Airworthy"
          },
          "totalFlightTime": {
            "value": 7329,
            "unit": "s",
            "display": "2h 02m"
          },
          "totalFlights": 7
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b58",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration",
          "makeModel": "DJI Matrice 30T",
          "serialNumber": "DJ7BW10313",
          "registrationNumber": "FA3XXX11YE",
          "status": {
            "level": "red",
            "label": "Grounded"
          },
          "totalFlightTime": {
            "value": 1206,
            "unit": "s",
            "display": "20m 06s"
          },
          "totalFlights": 2
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5b",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "makeModel": "DJI Matrice 350 RTK",
          "serialNumber": "DJDFV10626",
          "registrationNumber": "FA3XXX12PJ",
          "status": {
            "level": "amber",
            "label": "Expires in 19 days"
          },
          "totalFlightTime": {
            "value": 1994,
            "unit": "s",
            "display": "33m 14s"
          },
          "totalFlights": 3
        }
      ],
      "search": "",
      "statusFilter": "all",
      "canManage": true,
      "empty": {
        "title": "No aircraft yet",
        "body": "Add an aircraft to track its registration, Remote ID, flight hours, and maintenance.",
        "actionLabel": "Add aircraft"
      }
    },
    "aircraftDetail": {
      "loading": false,
      "error": null,
      "aircraft": {
        "id": "0199c4a0-0000-7000-8000-0000004c4b55",
        "name": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
        "makeModel": "DJI Mavic 3 Enterprise",
        "serialNumber": "DJ17X10000",
        "registrationNumber": "FA3XXX1179",
        "registrationExpires": {
          "iso": "2027-04-26",
          "absolute": "Apr 26, 2027",
          "relative": "in 7 months",
          "display": "Apr 26, 2027 — in 7 months",
          "daysFromToday": 200
        },
        "remoteId": "Standard Remote ID · 1581F4C4B40",
        "takeoffMass": {
          "value": 2.02,
          "unit": "lb",
          "display": "2.02 lb"
        },
        "firmwareVersion": "v1.0.0",
        "status": {
          "level": "green",
          "label": "Airworthy"
        },
        "groundedReason": null,
        "reasons": [],
        "totals": {
          "flights": 7,
          "flightTime": {
            "value": 7329,
            "unit": "s",
            "display": "2h 02m"
          }
        }
      },
      "recentFlights": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5f",
          "takeoff": {
            "iso": "2026-08-21T16:24:00.000Z",
            "absolute": "Aug 21, 2026, 10:24 AM MDT",
            "relative": "48 days ago",
            "display": "Aug 21, 2026, 10:24 AM MDT — 48 days ago",
            "daysFromToday": -48
          },
          "duration": {
            "value": 1778,
            "unit": "s",
            "display": "29m 38s"
          },
          "pilotName": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Cherry Creek Bridge — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 138,
            "unit": "ft",
            "display": "138 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b61",
          "takeoff": {
            "iso": "2026-05-23T18:15:00.000Z",
            "absolute": "May 23, 2026, 12:15 PM MDT",
            "relative": "5 months ago",
            "display": "May 23, 2026, 12:15 PM MDT — 5 months ago",
            "daysFromToday": -138
          },
          "duration": {
            "value": 1695,
            "unit": "s",
            "display": "28m 15s"
          },
          "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Castle Rock Quarry — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 305,
            "unit": "ft",
            "display": "305 ft"
          },
          "source": "manual",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b62",
          "takeoff": {
            "iso": "2026-04-10T16:46:00.000Z",
            "absolute": "Apr 10, 2026, 10:46 AM MDT",
            "relative": "6 months ago",
            "display": "Apr 10, 2026, 10:46 AM MDT — 6 months ago",
            "daysFromToday": -181
          },
          "duration": {
            "value": 507,
            "unit": "s",
            "display": "8m 27s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 305,
            "unit": "ft",
            "display": "305 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b63",
          "takeoff": {
            "iso": "2026-02-23T15:21:00.000Z",
            "absolute": "Feb 23, 2026, 8:21 AM MST",
            "relative": "7 months ago",
            "display": "Feb 23, 2026, 8:21 AM MST — 7 months ago",
            "daysFromToday": -227
          },
          "duration": {
            "value": 904,
            "unit": "s",
            "display": "15m 04s"
          },
          "pilotName": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Castle Rock Quarry — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 341,
            "unit": "ft",
            "display": "341 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b64",
          "takeoff": {
            "iso": "2026-01-09T16:40:00.000Z",
            "absolute": "Jan 9, 2026, 9:40 AM MST",
            "relative": "9 months ago",
            "display": "Jan 9, 2026, 9:40 AM MST — 9 months ago",
            "daysFromToday": -272
          },
          "duration": {
            "value": 659,
            "unit": "s",
            "display": "10m 59s"
          },
          "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Boulder Creek Levee — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 141,
            "unit": "ft",
            "display": "141 ft"
          },
          "source": "manual",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b65",
          "takeoff": {
            "iso": "2025-11-25T21:46:00.000Z",
            "absolute": "Nov 25, 2025, 2:46 PM MST",
            "relative": "10 months ago",
            "display": "Nov 25, 2025, 2:46 PM MST — 10 months ago",
            "daysFromToday": -317
          },
          "duration": {
            "value": 725,
            "unit": "s",
            "display": "12m 05s"
          },
          "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Henderson Solar Farm — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 180,
            "unit": "ft",
            "display": "180 ft"
          },
          "source": "import",
          "pendingSync": false
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b69",
          "takeoff": {
            "iso": "2025-05-30T21:57:00.000Z",
            "absolute": "May 30, 2025, 3:57 PM MDT",
            "relative": "16 months ago",
            "display": "May 30, 2025, 3:57 PM MDT — 16 months ago",
            "daysFromToday": -496
          },
          "duration": {
            "value": 1061,
            "unit": "s",
            "display": "17m 41s"
          },
          "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "locationName": "Lakewood Water Tower — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
          "maxAltitude": {
            "value": 164,
            "unit": "ft",
            "display": "164 ft"
          },
          "source": "import",
          "pendingSync": false
        }
      ],
      "batteries": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b56",
          "label": "Northern #1",
          "serialNumber": "BAT-01-01-7700",
          "cycleCount": 140,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-04-10T16:46:00.000Z",
            "absolute": "Apr 10, 2026, 10:46 AM MDT",
            "relative": "6 months ago",
            "display": "Apr 10, 2026, 10:46 AM MDT — 6 months ago",
            "daysFromToday": -181
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b57",
          "label": "Northern #2",
          "serialNumber": "BAT-01-02-7701",
          "cycleCount": 77,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-08-21T16:24:00.000Z",
            "absolute": "Aug 21, 2026, 10:24 AM MDT",
            "relative": "48 days ago",
            "display": "Aug 21, 2026, 10:24 AM MDT — 48 days ago",
            "daysFromToday": -48
          }
        }
      ],
      "canEdit": true,
      "canGround": true
    },
    "batteryList": {
      "loading": false,
      "error": null,
      "batteries": [
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b56",
          "label": "Northern #1",
          "serialNumber": "BAT-01-01-7700",
          "cycleCount": 140,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-04-10T16:46:00.000Z",
            "absolute": "Apr 10, 2026, 10:46 AM MDT",
            "relative": "6 months ago",
            "display": "Apr 10, 2026, 10:46 AM MDT — 6 months ago",
            "daysFromToday": -181
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b57",
          "label": "Northern #2",
          "serialNumber": "BAT-01-02-7701",
          "cycleCount": 77,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-08-21T16:24:00.000Z",
            "absolute": "Aug 21, 2026, 10:24 AM MDT",
            "relative": "48 days ago",
            "display": "Aug 21, 2026, 10:24 AM MDT — 48 days ago",
            "daysFromToday": -48
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b59",
          "label": "Northern #1",
          "serialNumber": "BAT-02-01-7731",
          "cycleCount": 153,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": null
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5a",
          "label": "Northern #2",
          "serialNumber": "BAT-02-02-7732",
          "cycleCount": 39,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-07-08T14:55:00.000Z",
            "absolute": "Jul 8, 2026, 8:55 AM MDT",
            "relative": "3 months ago",
            "display": "Jul 8, 2026, 8:55 AM MDT — 3 months ago",
            "daysFromToday": -92
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5c",
          "label": "Northern #1",
          "serialNumber": "BAT-03-01-7762",
          "cycleCount": 132,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": {
            "iso": "2026-10-06T14:27:00.000Z",
            "absolute": "Oct 6, 2026, 8:27 AM MDT",
            "relative": "2 days ago",
            "display": "Oct 6, 2026, 8:27 AM MDT — 2 days ago",
            "daysFromToday": -2
          }
        },
        {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5d",
          "label": "Northern #2",
          "serialNumber": "BAT-03-02-7763",
          "cycleCount": 125,
          "cycleLimit": 200,
          "status": {
            "level": "green",
            "label": "Healthy"
          },
          "lastUsed": null
        }
      ],
      "canManage": true,
      "empty": {
        "title": "No batteries yet",
        "body": "Add batteries to track cycle counts automatically from your flights and get retirement warnings.",
        "actionLabel": "Add battery"
      }
    },
    "flightList": {
      "loading": false,
      "error": null,
      "flights": {
        "items": [
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b5e",
            "takeoff": {
              "iso": "2026-10-06T14:27:00.000Z",
              "absolute": "Oct 6, 2026, 8:27 AM MDT",
              "relative": "2 days ago",
              "display": "Oct 6, 2026, 8:27 AM MDT — 2 days ago",
              "daysFromToday": -2
            },
            "duration": {
              "value": 750,
              "unit": "s",
              "display": "12m 30s"
            },
            "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
            "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 135,
              "unit": "ft",
              "display": "135 ft"
            },
            "source": "manual",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b5f",
            "takeoff": {
              "iso": "2026-08-21T16:24:00.000Z",
              "absolute": "Aug 21, 2026, 10:24 AM MDT",
              "relative": "48 days ago",
              "display": "Aug 21, 2026, 10:24 AM MDT — 48 days ago",
              "daysFromToday": -48
            },
            "duration": {
              "value": 1778,
              "unit": "s",
              "display": "29m 38s"
            },
            "pilotName": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Cherry Creek Bridge — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 138,
              "unit": "ft",
              "display": "138 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b60",
            "takeoff": {
              "iso": "2026-07-08T14:55:00.000Z",
              "absolute": "Jul 8, 2026, 8:55 AM MDT",
              "relative": "3 months ago",
              "display": "Jul 8, 2026, 8:55 AM MDT — 3 months ago",
              "daysFromToday": -92
            },
            "duration": {
              "value": 812,
              "unit": "s",
              "display": "13m 32s"
            },
            "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration",
            "locationName": "Cherry Creek Bridge — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 322,
              "unit": "ft",
              "display": "322 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b61",
            "takeoff": {
              "iso": "2026-05-23T18:15:00.000Z",
              "absolute": "May 23, 2026, 12:15 PM MDT",
              "relative": "5 months ago",
              "display": "May 23, 2026, 12:15 PM MDT — 5 months ago",
              "daysFromToday": -138
            },
            "duration": {
              "value": 1695,
              "unit": "s",
              "display": "28m 15s"
            },
            "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Castle Rock Quarry — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 305,
              "unit": "ft",
              "display": "305 ft"
            },
            "source": "manual",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b62",
            "takeoff": {
              "iso": "2026-04-10T16:46:00.000Z",
              "absolute": "Apr 10, 2026, 10:46 AM MDT",
              "relative": "6 months ago",
              "display": "Apr 10, 2026, 10:46 AM MDT — 6 months ago",
              "daysFromToday": -181
            },
            "duration": {
              "value": 507,
              "unit": "s",
              "display": "8m 27s"
            },
            "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 305,
              "unit": "ft",
              "display": "305 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b63",
            "takeoff": {
              "iso": "2026-02-23T15:21:00.000Z",
              "absolute": "Feb 23, 2026, 8:21 AM MST",
              "relative": "7 months ago",
              "display": "Feb 23, 2026, 8:21 AM MST — 7 months ago",
              "daysFromToday": -227
            },
            "duration": {
              "value": 904,
              "unit": "s",
              "display": "15m 04s"
            },
            "pilotName": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Castle Rock Quarry — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 341,
              "unit": "ft",
              "display": "341 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b64",
            "takeoff": {
              "iso": "2026-01-09T16:40:00.000Z",
              "absolute": "Jan 9, 2026, 9:40 AM MST",
              "relative": "9 months ago",
              "display": "Jan 9, 2026, 9:40 AM MST — 9 months ago",
              "daysFromToday": -272
            },
            "duration": {
              "value": 659,
              "unit": "s",
              "display": "10m 59s"
            },
            "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Boulder Creek Levee — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 141,
              "unit": "ft",
              "display": "141 ft"
            },
            "source": "manual",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b65",
            "takeoff": {
              "iso": "2025-11-25T21:46:00.000Z",
              "absolute": "Nov 25, 2025, 2:46 PM MST",
              "relative": "10 months ago",
              "display": "Nov 25, 2025, 2:46 PM MST — 10 months ago",
              "daysFromToday": -317
            },
            "duration": {
              "value": 725,
              "unit": "s",
              "display": "12m 05s"
            },
            "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Henderson Solar Farm — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 180,
              "unit": "ft",
              "display": "180 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b66",
            "takeoff": {
              "iso": "2025-10-12T21:16:00.000Z",
              "absolute": "Oct 12, 2025, 3:16 PM MDT",
              "relative": "12 months ago",
              "display": "Oct 12, 2025, 3:16 PM MDT — 12 months ago",
              "daysFromToday": -361
            },
            "duration": {
              "value": 740,
              "unit": "s",
              "display": "12m 20s"
            },
            "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
            "locationName": "Boulder Creek Levee — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 276,
              "unit": "ft",
              "display": "276 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b67",
            "takeoff": {
              "iso": "2025-08-28T17:29:00.000Z",
              "absolute": "Aug 28, 2025, 11:29 AM MDT",
              "relative": "13 months ago",
              "display": "Aug 28, 2025, 11:29 AM MDT — 13 months ago",
              "daysFromToday": -406
            },
            "duration": {
              "value": 394,
              "unit": "s",
              "display": "6m 34s"
            },
            "pilotName": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration",
            "locationName": "Lakewood Water Tower — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 292,
              "unit": "ft",
              "display": "292 ft"
            },
            "source": "manual",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b68",
            "takeoff": {
              "iso": "2025-07-13T20:07:00.000Z",
              "absolute": "Jul 13, 2025, 2:07 PM MDT",
              "relative": "15 months ago",
              "display": "Jul 13, 2025, 2:07 PM MDT — 15 months ago",
              "daysFromToday": -452
            },
            "duration": {
              "value": 504,
              "unit": "s",
              "display": "8m 24s"
            },
            "pilotName": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
            "locationName": "Golden Rooftop Survey — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 279,
              "unit": "ft",
              "display": "279 ft"
            },
            "source": "import",
            "pendingSync": false
          },
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b69",
            "takeoff": {
              "iso": "2025-05-30T21:57:00.000Z",
              "absolute": "May 30, 2025, 3:57 PM MDT",
              "relative": "16 months ago",
              "display": "May 30, 2025, 3:57 PM MDT — 16 months ago",
              "daysFromToday": -496
            },
            "duration": {
              "value": 1061,
              "unit": "s",
              "display": "17m 41s"
            },
            "pilotName": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
            "aircraftName": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
            "locationName": "Lakewood Water Tower — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
            "maxAltitude": {
              "value": 164,
              "unit": "ft",
              "display": "164 ft"
            },
            "source": "import",
            "pendingSync": false
          }
        ],
        "total": 12,
        "nextCursor": null
      },
      "filter": {
        "pilotId": null,
        "aircraftId": null,
        "from": null,
        "to": null
      },
      "pilotOptions": [
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b44",
          "label": "Maximilian Alexander Featherstonehaugh-Montgomery III"
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b4b",
          "label": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova"
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b51",
          "label": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine"
        }
      ],
      "aircraftOptions": [
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b55",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration"
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b58",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration"
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b5b",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration"
        }
      ],
      "totals": {
        "flights": 12,
        "flightTime": {
          "value": 10529,
          "unit": "s",
          "display": "2h 55m"
        }
      },
      "canLog": true,
      "empty": {
        "title": "No flights logged",
        "body": "Log a flight in seconds, or import logs from your flight controller to fill your logbook automatically.",
        "actionLabel": "Log a flight"
      }
    },
    "flightDetail": {
      "loading": false,
      "error": null,
      "flight": {
        "id": "0199c4a0-0000-7000-8000-0000004c4b5e",
        "takeoff": {
          "iso": "2026-10-06T14:27:00.000Z",
          "absolute": "Oct 6, 2026, 8:27 AM MDT",
          "relative": "2 days ago",
          "display": "Oct 6, 2026, 8:27 AM MDT — 2 days ago",
          "daysFromToday": -2
        },
        "landing": {
          "iso": "2026-10-06T14:39:30.000Z",
          "absolute": "Oct 6, 2026, 8:39 AM MDT",
          "relative": "2 days ago",
          "display": "Oct 6, 2026, 8:39 AM MDT — 2 days ago",
          "daysFromToday": -2
        },
        "duration": {
          "value": 750,
          "unit": "s",
          "display": "12m 30s"
        },
        "pilot": {
          "id": "0199c4a0-0000-7000-8000-0000004c4b44",
          "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "initials": "MI"
        },
        "observers": [
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b4b",
            "name": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
            "initials": "AV"
          }
        ],
        "aircraft": {
          "id": "0199c4a0-0000-7000-8000-0000004c4b5b",
          "name": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration"
        },
        "batteries": [
          {
            "id": "0199c4a0-0000-7000-8000-0000004c4b5c",
            "label": "Northern #1",
            "startPct": 100,
            "endPct": 20
          }
        ],
        "locationName": "Aurora Distribution Center — North Access Road Staging Area, Gate 14 (Contractor Entrance Only)",
        "maxAltitude": {
          "value": 135,
          "unit": "ft",
          "display": "135 ft"
        },
        "maxDistance": {
          "value": 1716,
          "unit": "ft",
          "display": "1,716 ft"
        },
        "operationType": "Commercial (Part 107)",
        "airspaceClass": "Class G",
        "authorizationRef": null,
        "weatherSummary": "Clear, 64 °F, wind 9 mph gusting 15 mph from 270°",
        "notes": "Gusty winds above 200 ft; RTH tested before mission.",
        "source": "Logged manually",
        "integrity": null
      },
      "path": null,
      "altitudeProfile": [
        {
          "t": 0,
          "altitude": 0
        },
        {
          "t": 33,
          "altitude": 11
        },
        {
          "t": 65,
          "altitude": 22
        },
        {
          "t": 98,
          "altitude": 34
        },
        {
          "t": 130,
          "altitude": 45
        },
        {
          "t": 163,
          "altitude": 56
        },
        {
          "t": 196,
          "altitude": 67
        },
        {
          "t": 228,
          "altitude": 78
        },
        {
          "t": 261,
          "altitude": 90
        },
        {
          "t": 293,
          "altitude": 101
        },
        {
          "t": 326,
          "altitude": 112
        },
        {
          "t": 359,
          "altitude": 123
        },
        {
          "t": 391,
          "altitude": 123
        },
        {
          "t": 424,
          "altitude": 112
        },
        {
          "t": 457,
          "altitude": 101
        },
        {
          "t": 489,
          "altitude": 90
        },
        {
          "t": 522,
          "altitude": 78
        },
        {
          "t": 554,
          "altitude": 67
        },
        {
          "t": 587,
          "altitude": 56
        },
        {
          "t": 620,
          "altitude": 45
        },
        {
          "t": 652,
          "altitude": 34
        },
        {
          "t": 685,
          "altitude": 22
        },
        {
          "t": 717,
          "altitude": 11
        },
        {
          "t": 750,
          "altitude": 0
        }
      ],
      "canEdit": true
    },
    "logFlight": {
      "loading": false,
      "error": null,
      "defaults": {
        "pilotId": "0199c4a0-0000-7000-8000-0000004c4b44",
        "aircraftId": "0199c4a0-0000-7000-8000-0000004c4b5b",
        "batteryIds": [
          "0199c4a0-0000-7000-8000-0000004c4b5c"
        ],
        "siteId": null,
        "operationType": "commercial",
        "takeoffAt": "2026-10-08T15:30:00.000Z",
        "durationMinutes": 13
      },
      "hasLastFlight": true,
      "pilotOptions": [
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b44",
          "label": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "status": {
            "level": "green",
            "label": "Current"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b4b",
          "label": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
          "status": {
            "level": "green",
            "label": "Current"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b51",
          "label": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
          "status": {
            "level": "green",
            "label": "Current"
          }
        }
      ],
      "aircraftOptions": [
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b55",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 1 — Thermal & LiDAR Configuration",
          "status": {
            "level": "green",
            "label": "Airworthy"
          },
          "recent": true
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b58",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 2 — Thermal & LiDAR Configuration",
          "status": {
            "level": "red",
            "label": "Grounded"
          },
          "recent": true
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b5b",
          "label": "Northern Colorado Regional Infrastructure Inspection Unit 3 — Thermal & LiDAR Configuration",
          "status": {
            "level": "amber",
            "label": "Expires in 19 days"
          },
          "recent": false
        }
      ],
      "batteryOptions": [
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b56",
          "label": "Northern #1",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b57",
          "label": "Northern #2",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b59",
          "label": "Northern #1",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b5a",
          "label": "Northern #2",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b5c",
          "label": "Northern #1",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        },
        {
          "value": "0199c4a0-0000-7000-8000-0000004c4b5d",
          "label": "Northern #2",
          "status": {
            "level": "green",
            "label": "Healthy"
          }
        }
      ],
      "siteOptions": [
        {
          "value": "site-1",
          "label": "Henderson Solar Farm",
          "recent": true
        },
        {
          "value": "site-2",
          "label": "Cherry Creek Bridge",
          "recent": true
        },
        {
          "value": "site-3",
          "label": "Riverside Substation",
          "recent": false
        },
        {
          "value": "site-4",
          "label": "Lakewood Water Tower",
          "recent": false
        },
        {
          "value": "site-5",
          "label": "Golden Rooftop Survey",
          "recent": false
        }
      ],
      "operationTypeOptions": [
        {
          "value": "commercial",
          "label": "Commercial (Part 107)"
        },
        {
          "value": "training",
          "label": "Training"
        },
        {
          "value": "public_safety",
          "label": "Public safety"
        },
        {
          "value": "maintenance_test",
          "label": "Maintenance test flight"
        },
        {
          "value": "other",
          "label": "Other"
        }
      ],
      "warnings": [],
      "altitudeUnitLabel": "ft",
      "fieldErrors": {},
      "saving": false
    },
    "rulePackAdmin": {
      "loading": false,
      "error": null,
      "pack": {
        "jurisdiction": "US-FAA-Part107",
        "name": "United States — FAA 14 CFR Part 107 (Small UAS)",
        "version": "1.0.0",
        "authority": "Federal Aviation Administration",
        "effectiveFrom": {
          "iso": "2021-04-21",
          "absolute": "Apr 21, 2021",
          "relative": "5.5 years ago",
          "display": "Apr 21, 2021 — 5.5 years ago",
          "daysFromToday": -1996
        },
        "disclaimer": "Values in this pack are provided for record-keeping convenience and are pending verification. Certa does not provide legal or regulatory advice; operators remain responsible for compliance with all applicable regulations.",
        "ruleCount": 19,
        "unverifiedCount": 19
      },
      "availableJurisdictions": [
        {
          "jurisdiction": "US-FAA-Part107",
          "name": "United States — FAA 14 CFR Part 107 (Small UAS)",
          "active": true
        }
      ],
      "credentialTypes": [
        {
          "id": "part107_certificate",
          "label": "Remote Pilot Certificate (Part 107)",
          "description": "Remote pilot certificate with small UAS rating. The certificate itself has no expiration date; currency is maintained through recurrent training or testing.",
          "validity": "Does not expire",
          "requiredForCurrency": true
        },
        {
          "id": "part107_initial_knowledge",
          "label": "Initial aeronautical knowledge test",
          "description": "Passing the initial knowledge test establishes currency for the recurrent period.",
          "validity": "24 calendar months (14 CFR 107.65)",
          "requiredForCurrency": false
        },
        {
          "id": "part107_recurrent",
          "label": "Recurrent training (Part 107)",
          "description": "Online recurrent training (or recurrent test) completed within the recency window required to exercise the privileges of the remote pilot certificate.",
          "validity": "24 calendar months (14 CFR 107.65)",
          "requiredForCurrency": true
        },
        {
          "id": "night_operations_training",
          "label": "Night operations training",
          "description": "Training or testing covering night operations, required before conducting operations at night. Satisfied by recurrent training/testing completed after the night-rule effective date.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        },
        {
          "id": "type_specific_training",
          "label": "Type-specific training",
          "description": "Manufacturer or operator training for a specific aircraft type. Expiry set per record.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        },
        {
          "id": "waiver_held",
          "label": "Waiver / certificate of waiver (pilot-held)",
          "description": "A Part 107 waiver issued to the pilot. Expiry is taken from the waiver document.",
          "validity": "Does not expire",
          "requiredForCurrency": false
        }
      ],
      "rules": [
        {
          "id": "pilot.aeronautical_knowledge.recency",
          "title": "Aeronautical knowledge recency",
          "description": "A remote pilot must have completed initial or recurrent aeronautical knowledge training or testing within the preceding period to act as remote pilot in command.",
          "appliesTo": "pilot",
          "valueDisplay": "24 months (calendar)",
          "packValueDisplay": null,
          "statedAs": "24 calendar months",
          "sourceCitation": "14 CFR 107.65",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-C/section-107.65",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "pilot.minimum_age",
          "title": "Minimum age for remote pilot certificate",
          "description": "Minimum age to be eligible for a remote pilot certificate.",
          "appliesTo": "pilot",
          "valueDisplay": "16",
          "packValueDisplay": null,
          "statedAs": "16 years of age",
          "sourceCitation": "14 CFR 107.61(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-C/section-107.61",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "integer"
        },
        {
          "id": "pilot.night_operations.training_required",
          "title": "Night operations require training",
          "description": "Operations at night require the remote pilot to have completed training or testing that covers night operations.",
          "appliesTo": "pilot",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.29(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.29",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "aircraft.registration.validity",
          "title": "Aircraft registration validity period",
          "description": "Period for which a small unmanned aircraft registration remains valid before renewal.",
          "appliesTo": "aircraft",
          "valueDisplay": "3 years",
          "packValueDisplay": null,
          "statedAs": "3 years",
          "sourceCitation": "14 CFR 48.100",
          "sourceTitle": "14 CFR Part 48",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-C/part-48",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "aircraft.max_takeoff_mass",
          "title": "Maximum takeoff mass for a small UAS",
          "description": "A small unmanned aircraft must weigh less than this value at takeoff, including everything on board or otherwise attached.",
          "appliesTo": "aircraft",
          "valueDisplay": "55 lb",
          "packValueDisplay": null,
          "statedAs": "less than 55 pounds",
          "sourceCitation": "14 CFR 107.3 (definition of small unmanned aircraft)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.3",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "mass"
        },
        {
          "id": "aircraft.registration.min_mass",
          "title": "Registration mass threshold",
          "description": "Mass above which registration is required for aircraft operated recreationally. Under Part 107 every aircraft must be registered regardless of mass (see aircraft.registration.required_part107).",
          "appliesTo": "aircraft",
          "valueDisplay": "0.55 lb",
          "packValueDisplay": null,
          "statedAs": "more than 0.55 pounds (250 grams)",
          "sourceCitation": "14 CFR 48.15",
          "sourceTitle": "14 CFR Part 48",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-C/part-48",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "mass"
        },
        {
          "id": "aircraft.registration.required_part107",
          "title": "Registration required for all Part 107 aircraft",
          "description": "Aircraft operated under Part 107 must be registered regardless of mass.",
          "appliesTo": "aircraft",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.13",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.13",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "aircraft.remote_id.required",
          "title": "Remote ID required",
          "description": "Aircraft must comply with Remote ID by standard Remote ID, a broadcast module, or by operating within an FAA-recognized identification area (FRIA).",
          "appliesTo": "aircraft",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 89.105",
          "sourceTitle": "14 CFR Part 89",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-89",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "operation.max_altitude_agl",
          "title": "Maximum altitude above ground level",
          "description": "Maximum altitude above ground level, unless flown within a 400-foot radius of a structure and not higher than 400 feet above the structure's immediate uppermost limit.",
          "appliesTo": "operation",
          "valueDisplay": "300 ft (91.4 m)",
          "packValueDisplay": "400 ft (121.9 m)",
          "statedAs": "400 feet AGL",
          "sourceCitation": "14 CFR 107.51(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": {
            "reason": "Company SOP caps altitude at 300 ft",
            "setBy": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "setAt": {
              "iso": "2026-10-07T21:14:09.000Z",
              "absolute": "Oct 7, 2026, 3:14 PM MDT",
              "relative": "yesterday",
              "display": "Oct 7, 2026, 3:14 PM MDT — yesterday",
              "daysFromToday": -1
            }
          },
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.max_groundspeed",
          "title": "Maximum groundspeed",
          "description": "Maximum groundspeed of the small unmanned aircraft.",
          "appliesTo": "operation",
          "valueDisplay": "100 mph",
          "packValueDisplay": null,
          "statedAs": "87 knots (100 miles per hour)",
          "sourceCitation": "14 CFR 107.51(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "speed"
        },
        {
          "id": "operation.min_flight_visibility",
          "title": "Minimum flight visibility",
          "description": "Minimum flight visibility from the control station.",
          "appliesTo": "operation",
          "valueDisplay": "15,840 ft (4,828 m)",
          "packValueDisplay": null,
          "statedAs": "3 statute miles",
          "sourceCitation": "14 CFR 107.51(c)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.cloud_clearance_below",
          "title": "Minimum distance below clouds",
          "description": "Minimum vertical distance below clouds.",
          "appliesTo": "operation",
          "valueDisplay": "500 ft (152.4 m)",
          "packValueDisplay": null,
          "statedAs": "500 feet below the cloud",
          "sourceCitation": "14 CFR 107.51(d)(1)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.cloud_clearance_horizontal",
          "title": "Minimum horizontal distance from clouds",
          "description": "Minimum horizontal distance from clouds.",
          "appliesTo": "operation",
          "valueDisplay": "2,000 ft (609.6 m)",
          "packValueDisplay": null,
          "statedAs": "2,000 feet horizontally from the cloud",
          "sourceCitation": "14 CFR 107.51(d)(2)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.51",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.night_anticollision_lighting_visibility",
          "title": "Anti-collision lighting visibility (night / civil twilight)",
          "description": "Operations at night or during civil twilight require anti-collision lighting visible for at least this distance.",
          "appliesTo": "operation",
          "valueDisplay": "15,840 ft (4,828 m)",
          "packValueDisplay": null,
          "statedAs": "3 statute miles",
          "sourceCitation": "14 CFR 107.29(a)(2), 107.29(c)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-B/section-107.29",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "length"
        },
        {
          "id": "operation.remote_id.enforcement_date",
          "title": "Remote ID operating requirement date",
          "description": "Date from which operators must comply with Remote ID operating requirements.",
          "appliesTo": "operation",
          "valueDisplay": "Sep 16, 2023",
          "packValueDisplay": null,
          "statedAs": "September 16, 2023 (FAA exercised enforcement discretion until March 16, 2024)",
          "sourceCitation": "14 CFR 89.105; FAA enforcement policy statement",
          "sourceTitle": "14 CFR Part 89",
          "sourceUrl": "https://www.faa.gov/uas/getting_started/remote_id",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "date"
        },
        {
          "id": "incident.report.deadline",
          "title": "Accident reporting deadline",
          "description": "Time after an accident within which the remote pilot in command must report it to the FAA when it meets a reporting threshold.",
          "appliesTo": "incident",
          "valueDisplay": "10 days",
          "packValueDisplay": null,
          "statedAs": "within 10 calendar days",
          "sourceCitation": "14 CFR 107.9",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "duration"
        },
        {
          "id": "incident.report.injury_min_ais_level",
          "title": "Reportable injury threshold (AIS)",
          "description": "An accident causing serious injury to any person is reportable. Modelled as an injury of at least this level on the Abbreviated Injury Scale.",
          "appliesTo": "incident",
          "valueDisplay": "3",
          "packValueDisplay": null,
          "statedAs": "Serious injury — AIS level 3 or higher",
          "sourceCitation": "14 CFR 107.9(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "integer"
        },
        {
          "id": "incident.report.loss_of_consciousness",
          "title": "Loss of consciousness is reportable",
          "description": "An accident causing any loss of consciousness is reportable.",
          "appliesTo": "incident",
          "valueDisplay": "Yes",
          "packValueDisplay": null,
          "statedAs": null,
          "sourceCitation": "14 CFR 107.9(a)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "boolean"
        },
        {
          "id": "incident.report.property_damage_min",
          "title": "Reportable property damage threshold",
          "description": "Damage to any property, other than the small unmanned aircraft, is reportable when the cost of repair (including materials and labor) or fair market value in the event of total loss exceeds this amount.",
          "appliesTo": "incident",
          "valueDisplay": "500.00 USD",
          "packValueDisplay": null,
          "statedAs": "greater than $500",
          "sourceCitation": "14 CFR 107.9(b)",
          "sourceTitle": "14 CFR Part 107",
          "sourceUrl": "https://www.ecfr.gov/current/title-14/chapter-I/subchapter-F/part-107/subpart-A/section-107.9",
          "lastVerified": null,
          "needsVerification": true,
          "override": null,
          "canOverride": true,
          "valueKind": "money"
        }
      ],
      "filter": {
        "search": "",
        "appliesTo": null,
        "unverifiedOnly": false
      },
      "empty": {
        "title": "No rules match",
        "body": "Try clearing the search or filters.",
        "actionLabel": null
      }
    },
    "membersAdmin": {
      "loading": false,
      "error": null,
      "members": [
        {
          "membershipId": "0199c4a0-0000-7000-8000-0000004c4b43",
          "user": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b42",
            "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "initials": "MI"
          },
          "email": "maximilian.alexander.featherstonehaugh.montgomery.iii@example.com",
          "role": "owner",
          "roleLabel": "Owner",
          "expires": null,
          "joined": {
            "iso": "2025-01-10T15:30:00.000Z",
            "absolute": "Jan 10, 2025, 8:30 AM MST",
            "relative": "21 months ago",
            "display": "Jan 10, 2025, 8:30 AM MST — 21 months ago",
            "daysFromToday": -636
          },
          "isSelf": true
        },
        {
          "membershipId": "0199c4a0-0000-7000-8000-0000004c4b4a",
          "user": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b49",
            "name": "Anastasia Konstantinovna Vasilyeva-Rimsky-Korsakova",
            "initials": "AV"
          },
          "email": "anastasia.konstantinovna.vasilyeva.rimsky.korsakova@example.com",
          "role": "pilot",
          "roleLabel": "Pilot",
          "expires": null,
          "joined": {
            "iso": "2025-02-11T15:30:00.000Z",
            "absolute": "Feb 11, 2025, 8:30 AM MST",
            "relative": "20 months ago",
            "display": "Feb 11, 2025, 8:30 AM MST — 20 months ago",
            "daysFromToday": -604
          },
          "isSelf": false
        },
        {
          "membershipId": "0199c4a0-0000-7000-8000-0000004c4b50",
          "user": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b4f",
            "name": "Jean-Baptiste Emmanuel Zorg de la Croix-Fontaine",
            "initials": "JC"
          },
          "email": "jean.baptiste.emmanuel.zorg.de.la.croix.fontaine@example.com",
          "role": "pilot",
          "roleLabel": "Pilot",
          "expires": null,
          "joined": {
            "iso": "2025-03-12T15:30:00.000Z",
            "absolute": "Mar 12, 2025, 9:30 AM MDT",
            "relative": "19 months ago",
            "display": "Mar 12, 2025, 9:30 AM MDT — 19 months ago",
            "daysFromToday": -575
          },
          "isSelf": false
        }
      ],
      "roleOptions": [
        {
          "value": "owner",
          "label": "Owner",
          "description": "Everything, including billing and rule-pack overrides."
        },
        {
          "value": "admin",
          "label": "Admin",
          "description": "Everything except billing."
        },
        {
          "value": "chief_pilot",
          "label": "Chief Pilot",
          "description": "Manage pilots, missions, checklists, and approvals."
        },
        {
          "value": "pilot",
          "label": "Pilot",
          "description": "Log own flights, run checklists, report incidents, view assigned missions."
        },
        {
          "value": "maintenance_tech",
          "label": "Maintenance Tech",
          "description": "Maintenance events, components, batteries, and grounding."
        },
        {
          "value": "viewer",
          "label": "Viewer",
          "description": "Read-only access."
        },
        {
          "value": "auditor",
          "label": "Auditor",
          "description": "Time-boxed, read-only access to a defined scope. Every view is logged."
        }
      ],
      "canManage": true,
      "empty": {
        "title": "Just you so far",
        "body": "Invite pilots, maintenance techs, or an auditor. Each person gets a sign-in link by email.",
        "actionLabel": "Invite someone"
      }
    },
    "orgSettings": {
      "loading": false,
      "error": null,
      "values": {
        "name": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program",
        "timezone": "America/Denver",
        "units": {
          "length": "ft",
          "speed": "mph",
          "mass": "lb",
          "temperature": "F"
        },
        "defaultJurisdiction": "US-FAA-Part107"
      },
      "options": {
        "timezones": [
          {
            "value": "America/Denver",
            "label": "America/Denver"
          },
          {
            "value": "America/New_York",
            "label": "America/New York"
          },
          {
            "value": "America/Chicago",
            "label": "America/Chicago"
          },
          {
            "value": "America/Los_Angeles",
            "label": "America/Los Angeles"
          },
          {
            "value": "America/Phoenix",
            "label": "America/Phoenix"
          },
          {
            "value": "America/Anchorage",
            "label": "America/Anchorage"
          },
          {
            "value": "Pacific/Honolulu",
            "label": "Pacific/Honolulu"
          },
          {
            "value": "UTC",
            "label": "UTC"
          }
        ],
        "length": [
          {
            "value": "ft",
            "label": "Feet"
          },
          {
            "value": "m",
            "label": "Metres"
          }
        ],
        "speed": [
          {
            "value": "mph",
            "label": "mph"
          },
          {
            "value": "kph",
            "label": "km/h"
          },
          {
            "value": "kt",
            "label": "Knots"
          },
          {
            "value": "mps",
            "label": "m/s"
          }
        ],
        "mass": [
          {
            "value": "lb",
            "label": "Pounds"
          },
          {
            "value": "kg",
            "label": "Kilograms"
          },
          {
            "value": "g",
            "label": "Grams"
          }
        ],
        "temperature": [
          {
            "value": "F",
            "label": "°F"
          },
          {
            "value": "C",
            "label": "°C"
          }
        ],
        "jurisdictions": [
          {
            "value": "US-FAA-Part107",
            "label": "United States — FAA Part 107"
          }
        ]
      },
      "canEdit": true,
      "saving": false
    },
    "auditLog": {
      "loading": false,
      "error": null,
      "events": [
        {
          "id": 1004,
          "at": {
            "iso": "2026-10-07T21:14:09.000Z",
            "absolute": "Oct 7, 2026, 3:14 PM MDT",
            "relative": "yesterday",
            "display": "Oct 7, 2026, 3:14 PM MDT — yesterday",
            "daysFromToday": -1
          },
          "actor": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b42",
            "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "initials": "MI"
          },
          "actorLabel": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "entityLabel": "Rule override",
          "operation": "created",
          "changes": [
            {
              "field": "rule_id",
              "before": null,
              "after": "operation.max_altitude_agl"
            },
            {
              "field": "value",
              "before": null,
              "after": "91.44"
            },
            {
              "field": "reason",
              "before": null,
              "after": "Company SOP caps altitude at 300 ft"
            }
          ]
        },
        {
          "id": 1003,
          "at": {
            "iso": "2026-10-06T18:02:44.000Z",
            "absolute": "Oct 6, 2026, 12:02 PM MDT",
            "relative": "2 days ago",
            "display": "Oct 6, 2026, 12:02 PM MDT — 2 days ago",
            "daysFromToday": -2
          },
          "actor": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b42",
            "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "initials": "MI"
          },
          "actorLabel": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "entityLabel": "Aircraft",
          "operation": "updated",
          "changes": [
            {
              "field": "status",
              "before": "active",
              "after": "grounded"
            },
            {
              "field": "grounded_reason",
              "before": null,
              "after": "Gimbal damage after hard landing — incident open"
            }
          ]
        },
        {
          "id": 1002,
          "at": {
            "iso": "2026-10-02T03:40:00.000Z",
            "absolute": "Oct 1, 2026, 9:40 PM MDT",
            "relative": "7 days ago",
            "display": "Oct 1, 2026, 9:40 PM MDT — 7 days ago",
            "daysFromToday": -7
          },
          "actor": null,
          "actorLabel": "Direct database change",
          "entityLabel": "Flight",
          "operation": "updated",
          "changes": [
            {
              "field": "duration_seconds",
              "before": "900",
              "after": "1500"
            }
          ]
        },
        {
          "id": 1001,
          "at": {
            "iso": "2025-01-15T17:00:00.000Z",
            "absolute": "Jan 15, 2025, 10:00 AM MST",
            "relative": "21 months ago",
            "display": "Jan 15, 2025, 10:00 AM MST — 21 months ago",
            "daysFromToday": -631
          },
          "actor": {
            "id": "0199c4a0-0000-7000-8000-0000004c4b42",
            "name": "Maximilian Alexander Featherstonehaugh-Montgomery III",
            "initials": "MI"
          },
          "actorLabel": "Maximilian Alexander Featherstonehaugh-Montgomery III",
          "entityLabel": "Organization",
          "operation": "created",
          "changes": [
            {
              "field": "name",
              "before": null,
              "after": "Northern Colorado Regional Infrastructure Inspection & Emergency Response Unmanned Aircraft Systems Program"
            },
            {
              "field": "timezone",
              "before": null,
              "after": "America/Denver"
            }
          ]
        }
      ],
      "hasMore": false,
      "filter": {
        "entity": null,
        "actorUserId": null
      },
      "entityOptions": [
        {
          "value": "flights",
          "label": "Flights"
        },
        {
          "value": "aircraft",
          "label": "Aircraft"
        },
        {
          "value": "pilots",
          "label": "Pilots"
        },
        {
          "value": "credentials",
          "label": "Credentials"
        },
        {
          "value": "org_rule_overrides",
          "label": "Rule overrides"
        },
        {
          "value": "memberships",
          "label": "Members"
        }
      ],
      "empty": {
        "title": "No changes recorded yet",
        "body": "Every change to your records will appear here with who made it and what changed.",
        "actionLabel": null
      }
    },
    "syncConflicts": {
      "loading": false,
      "error": null,
      "conflicts": [],
      "empty": {
        "title": "Everything is in sync",
        "body": "Changes made offline sync automatically. Anything that needs a decision will appear here.",
        "actionLabel": null
      }
    }
  }
} satisfies FixtureScenario;
